//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GARecruitmentEntities : DbContext
    {
        public GARecruitmentEntities()
            : base("name=GARecruitmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Score> Scores { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Result> Results { get; set; }
    
        public virtual ObjectResult<ColumnNameSelect_Result> ColumnNameSelect(string tableName)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("TableName", tableName) :
                new ObjectParameter("TableName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ColumnNameSelect_Result>("ColumnNameSelect", tableNameParameter);
        }
    
        public virtual int ScoresInsert(Nullable<System.Guid> id, Nullable<System.DateTime> dateCreated, string fullName, string birthday, Nullable<int> pI_P1, Nullable<int> pI_P2, Nullable<int> pI_P3, Nullable<int> pI_P4, Nullable<int> pI_P5, Nullable<int> pI_P6, Nullable<int> pI_P7, Nullable<int> pI_P8, Nullable<int> pI_P9, Nullable<int> pI_P10, Nullable<int> pI_P11, Nullable<int> pI_P12, Nullable<int> pI_P13, Nullable<int> pI_E1, Nullable<int> pI_E2, Nullable<int> pI_E3, Nullable<int> pI_E4, Nullable<int> pI_E5, Nullable<int> pI_E6, Nullable<int> pI_E7, Nullable<int> pI_E8, Nullable<int> pI_E9, Nullable<int> pI_E10, Nullable<int> pI_E11, Nullable<int> pI_E12, Nullable<int> pI_E13, Nullable<int> pII_P1, Nullable<int> pII_P2, Nullable<int> pII_P3, Nullable<int> pII_P4, Nullable<int> pII_P5, Nullable<int> pII_P6, Nullable<int> pII_P7, Nullable<int> pII_P8, Nullable<int> pII_P9, Nullable<int> pII_P10, Nullable<int> pII_P11, Nullable<int> pII_P12, Nullable<int> pII_P13, Nullable<int> pII_E1, Nullable<int> pII_E2, Nullable<int> pII_E3, Nullable<int> pII_E4, Nullable<int> pII_E5, Nullable<int> pII_E6, Nullable<int> pII_E7, Nullable<int> pII_E8, Nullable<int> pII_E9, Nullable<int> pII_E10, Nullable<int> pII_E11, Nullable<int> pII_E12, Nullable<int> pII_E13, Nullable<int> pI_SumPear, Nullable<int> pI_SumEven, Nullable<int> pII_SumPear, Nullable<int> pII_SumEven, Nullable<int> totalPear, Nullable<int> totalEven, Nullable<int> percent, Nullable<int> difference, string ketQua, Nullable<int> scorePicture, Nullable<int> percentPicture, string ketQuaPicture, Nullable<int> scoreEye, string ketQuaEye)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            var dateCreatedParameter = dateCreated.HasValue ?
                new ObjectParameter("DateCreated", dateCreated) :
                new ObjectParameter("DateCreated", typeof(System.DateTime));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var birthdayParameter = birthday != null ?
                new ObjectParameter("Birthday", birthday) :
                new ObjectParameter("Birthday", typeof(string));
    
            var pI_P1Parameter = pI_P1.HasValue ?
                new ObjectParameter("PI_P1", pI_P1) :
                new ObjectParameter("PI_P1", typeof(int));
    
            var pI_P2Parameter = pI_P2.HasValue ?
                new ObjectParameter("PI_P2", pI_P2) :
                new ObjectParameter("PI_P2", typeof(int));
    
            var pI_P3Parameter = pI_P3.HasValue ?
                new ObjectParameter("PI_P3", pI_P3) :
                new ObjectParameter("PI_P3", typeof(int));
    
            var pI_P4Parameter = pI_P4.HasValue ?
                new ObjectParameter("PI_P4", pI_P4) :
                new ObjectParameter("PI_P4", typeof(int));
    
            var pI_P5Parameter = pI_P5.HasValue ?
                new ObjectParameter("PI_P5", pI_P5) :
                new ObjectParameter("PI_P5", typeof(int));
    
            var pI_P6Parameter = pI_P6.HasValue ?
                new ObjectParameter("PI_P6", pI_P6) :
                new ObjectParameter("PI_P6", typeof(int));
    
            var pI_P7Parameter = pI_P7.HasValue ?
                new ObjectParameter("PI_P7", pI_P7) :
                new ObjectParameter("PI_P7", typeof(int));
    
            var pI_P8Parameter = pI_P8.HasValue ?
                new ObjectParameter("PI_P8", pI_P8) :
                new ObjectParameter("PI_P8", typeof(int));
    
            var pI_P9Parameter = pI_P9.HasValue ?
                new ObjectParameter("PI_P9", pI_P9) :
                new ObjectParameter("PI_P9", typeof(int));
    
            var pI_P10Parameter = pI_P10.HasValue ?
                new ObjectParameter("PI_P10", pI_P10) :
                new ObjectParameter("PI_P10", typeof(int));
    
            var pI_P11Parameter = pI_P11.HasValue ?
                new ObjectParameter("PI_P11", pI_P11) :
                new ObjectParameter("PI_P11", typeof(int));
    
            var pI_P12Parameter = pI_P12.HasValue ?
                new ObjectParameter("PI_P12", pI_P12) :
                new ObjectParameter("PI_P12", typeof(int));
    
            var pI_P13Parameter = pI_P13.HasValue ?
                new ObjectParameter("PI_P13", pI_P13) :
                new ObjectParameter("PI_P13", typeof(int));
    
            var pI_E1Parameter = pI_E1.HasValue ?
                new ObjectParameter("PI_E1", pI_E1) :
                new ObjectParameter("PI_E1", typeof(int));
    
            var pI_E2Parameter = pI_E2.HasValue ?
                new ObjectParameter("PI_E2", pI_E2) :
                new ObjectParameter("PI_E2", typeof(int));
    
            var pI_E3Parameter = pI_E3.HasValue ?
                new ObjectParameter("PI_E3", pI_E3) :
                new ObjectParameter("PI_E3", typeof(int));
    
            var pI_E4Parameter = pI_E4.HasValue ?
                new ObjectParameter("PI_E4", pI_E4) :
                new ObjectParameter("PI_E4", typeof(int));
    
            var pI_E5Parameter = pI_E5.HasValue ?
                new ObjectParameter("PI_E5", pI_E5) :
                new ObjectParameter("PI_E5", typeof(int));
    
            var pI_E6Parameter = pI_E6.HasValue ?
                new ObjectParameter("PI_E6", pI_E6) :
                new ObjectParameter("PI_E6", typeof(int));
    
            var pI_E7Parameter = pI_E7.HasValue ?
                new ObjectParameter("PI_E7", pI_E7) :
                new ObjectParameter("PI_E7", typeof(int));
    
            var pI_E8Parameter = pI_E8.HasValue ?
                new ObjectParameter("PI_E8", pI_E8) :
                new ObjectParameter("PI_E8", typeof(int));
    
            var pI_E9Parameter = pI_E9.HasValue ?
                new ObjectParameter("PI_E9", pI_E9) :
                new ObjectParameter("PI_E9", typeof(int));
    
            var pI_E10Parameter = pI_E10.HasValue ?
                new ObjectParameter("PI_E10", pI_E10) :
                new ObjectParameter("PI_E10", typeof(int));
    
            var pI_E11Parameter = pI_E11.HasValue ?
                new ObjectParameter("PI_E11", pI_E11) :
                new ObjectParameter("PI_E11", typeof(int));
    
            var pI_E12Parameter = pI_E12.HasValue ?
                new ObjectParameter("PI_E12", pI_E12) :
                new ObjectParameter("PI_E12", typeof(int));
    
            var pI_E13Parameter = pI_E13.HasValue ?
                new ObjectParameter("PI_E13", pI_E13) :
                new ObjectParameter("PI_E13", typeof(int));
    
            var pII_P1Parameter = pII_P1.HasValue ?
                new ObjectParameter("PII_P1", pII_P1) :
                new ObjectParameter("PII_P1", typeof(int));
    
            var pII_P2Parameter = pII_P2.HasValue ?
                new ObjectParameter("PII_P2", pII_P2) :
                new ObjectParameter("PII_P2", typeof(int));
    
            var pII_P3Parameter = pII_P3.HasValue ?
                new ObjectParameter("PII_P3", pII_P3) :
                new ObjectParameter("PII_P3", typeof(int));
    
            var pII_P4Parameter = pII_P4.HasValue ?
                new ObjectParameter("PII_P4", pII_P4) :
                new ObjectParameter("PII_P4", typeof(int));
    
            var pII_P5Parameter = pII_P5.HasValue ?
                new ObjectParameter("PII_P5", pII_P5) :
                new ObjectParameter("PII_P5", typeof(int));
    
            var pII_P6Parameter = pII_P6.HasValue ?
                new ObjectParameter("PII_P6", pII_P6) :
                new ObjectParameter("PII_P6", typeof(int));
    
            var pII_P7Parameter = pII_P7.HasValue ?
                new ObjectParameter("PII_P7", pII_P7) :
                new ObjectParameter("PII_P7", typeof(int));
    
            var pII_P8Parameter = pII_P8.HasValue ?
                new ObjectParameter("PII_P8", pII_P8) :
                new ObjectParameter("PII_P8", typeof(int));
    
            var pII_P9Parameter = pII_P9.HasValue ?
                new ObjectParameter("PII_P9", pII_P9) :
                new ObjectParameter("PII_P9", typeof(int));
    
            var pII_P10Parameter = pII_P10.HasValue ?
                new ObjectParameter("PII_P10", pII_P10) :
                new ObjectParameter("PII_P10", typeof(int));
    
            var pII_P11Parameter = pII_P11.HasValue ?
                new ObjectParameter("PII_P11", pII_P11) :
                new ObjectParameter("PII_P11", typeof(int));
    
            var pII_P12Parameter = pII_P12.HasValue ?
                new ObjectParameter("PII_P12", pII_P12) :
                new ObjectParameter("PII_P12", typeof(int));
    
            var pII_P13Parameter = pII_P13.HasValue ?
                new ObjectParameter("PII_P13", pII_P13) :
                new ObjectParameter("PII_P13", typeof(int));
    
            var pII_E1Parameter = pII_E1.HasValue ?
                new ObjectParameter("PII_E1", pII_E1) :
                new ObjectParameter("PII_E1", typeof(int));
    
            var pII_E2Parameter = pII_E2.HasValue ?
                new ObjectParameter("PII_E2", pII_E2) :
                new ObjectParameter("PII_E2", typeof(int));
    
            var pII_E3Parameter = pII_E3.HasValue ?
                new ObjectParameter("PII_E3", pII_E3) :
                new ObjectParameter("PII_E3", typeof(int));
    
            var pII_E4Parameter = pII_E4.HasValue ?
                new ObjectParameter("PII_E4", pII_E4) :
                new ObjectParameter("PII_E4", typeof(int));
    
            var pII_E5Parameter = pII_E5.HasValue ?
                new ObjectParameter("PII_E5", pII_E5) :
                new ObjectParameter("PII_E5", typeof(int));
    
            var pII_E6Parameter = pII_E6.HasValue ?
                new ObjectParameter("PII_E6", pII_E6) :
                new ObjectParameter("PII_E6", typeof(int));
    
            var pII_E7Parameter = pII_E7.HasValue ?
                new ObjectParameter("PII_E7", pII_E7) :
                new ObjectParameter("PII_E7", typeof(int));
    
            var pII_E8Parameter = pII_E8.HasValue ?
                new ObjectParameter("PII_E8", pII_E8) :
                new ObjectParameter("PII_E8", typeof(int));
    
            var pII_E9Parameter = pII_E9.HasValue ?
                new ObjectParameter("PII_E9", pII_E9) :
                new ObjectParameter("PII_E9", typeof(int));
    
            var pII_E10Parameter = pII_E10.HasValue ?
                new ObjectParameter("PII_E10", pII_E10) :
                new ObjectParameter("PII_E10", typeof(int));
    
            var pII_E11Parameter = pII_E11.HasValue ?
                new ObjectParameter("PII_E11", pII_E11) :
                new ObjectParameter("PII_E11", typeof(int));
    
            var pII_E12Parameter = pII_E12.HasValue ?
                new ObjectParameter("PII_E12", pII_E12) :
                new ObjectParameter("PII_E12", typeof(int));
    
            var pII_E13Parameter = pII_E13.HasValue ?
                new ObjectParameter("PII_E13", pII_E13) :
                new ObjectParameter("PII_E13", typeof(int));
    
            var pI_SumPearParameter = pI_SumPear.HasValue ?
                new ObjectParameter("PI_SumPear", pI_SumPear) :
                new ObjectParameter("PI_SumPear", typeof(int));
    
            var pI_SumEvenParameter = pI_SumEven.HasValue ?
                new ObjectParameter("PI_SumEven", pI_SumEven) :
                new ObjectParameter("PI_SumEven", typeof(int));
    
            var pII_SumPearParameter = pII_SumPear.HasValue ?
                new ObjectParameter("PII_SumPear", pII_SumPear) :
                new ObjectParameter("PII_SumPear", typeof(int));
    
            var pII_SumEvenParameter = pII_SumEven.HasValue ?
                new ObjectParameter("PII_SumEven", pII_SumEven) :
                new ObjectParameter("PII_SumEven", typeof(int));
    
            var totalPearParameter = totalPear.HasValue ?
                new ObjectParameter("TotalPear", totalPear) :
                new ObjectParameter("TotalPear", typeof(int));
    
            var totalEvenParameter = totalEven.HasValue ?
                new ObjectParameter("TotalEven", totalEven) :
                new ObjectParameter("TotalEven", typeof(int));
    
            var percentParameter = percent.HasValue ?
                new ObjectParameter("Percent", percent) :
                new ObjectParameter("Percent", typeof(int));
    
            var differenceParameter = difference.HasValue ?
                new ObjectParameter("Difference", difference) :
                new ObjectParameter("Difference", typeof(int));
    
            var ketQuaParameter = ketQua != null ?
                new ObjectParameter("KetQua", ketQua) :
                new ObjectParameter("KetQua", typeof(string));
    
            var scorePictureParameter = scorePicture.HasValue ?
                new ObjectParameter("ScorePicture", scorePicture) :
                new ObjectParameter("ScorePicture", typeof(int));
    
            var percentPictureParameter = percentPicture.HasValue ?
                new ObjectParameter("PercentPicture", percentPicture) :
                new ObjectParameter("PercentPicture", typeof(int));
    
            var ketQuaPictureParameter = ketQuaPicture != null ?
                new ObjectParameter("KetQuaPicture", ketQuaPicture) :
                new ObjectParameter("KetQuaPicture", typeof(string));
    
            var scoreEyeParameter = scoreEye.HasValue ?
                new ObjectParameter("ScoreEye", scoreEye) :
                new ObjectParameter("ScoreEye", typeof(int));
    
            var ketQuaEyeParameter = ketQuaEye != null ?
                new ObjectParameter("KetQuaEye", ketQuaEye) :
                new ObjectParameter("KetQuaEye", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ScoresInsert", idParameter, dateCreatedParameter, fullNameParameter, birthdayParameter, pI_P1Parameter, pI_P2Parameter, pI_P3Parameter, pI_P4Parameter, pI_P5Parameter, pI_P6Parameter, pI_P7Parameter, pI_P8Parameter, pI_P9Parameter, pI_P10Parameter, pI_P11Parameter, pI_P12Parameter, pI_P13Parameter, pI_E1Parameter, pI_E2Parameter, pI_E3Parameter, pI_E4Parameter, pI_E5Parameter, pI_E6Parameter, pI_E7Parameter, pI_E8Parameter, pI_E9Parameter, pI_E10Parameter, pI_E11Parameter, pI_E12Parameter, pI_E13Parameter, pII_P1Parameter, pII_P2Parameter, pII_P3Parameter, pII_P4Parameter, pII_P5Parameter, pII_P6Parameter, pII_P7Parameter, pII_P8Parameter, pII_P9Parameter, pII_P10Parameter, pII_P11Parameter, pII_P12Parameter, pII_P13Parameter, pII_E1Parameter, pII_E2Parameter, pII_E3Parameter, pII_E4Parameter, pII_E5Parameter, pII_E6Parameter, pII_E7Parameter, pII_E8Parameter, pII_E9Parameter, pII_E10Parameter, pII_E11Parameter, pII_E12Parameter, pII_E13Parameter, pI_SumPearParameter, pI_SumEvenParameter, pII_SumPearParameter, pII_SumEvenParameter, totalPearParameter, totalEvenParameter, percentParameter, differenceParameter, ketQuaParameter, scorePictureParameter, percentPictureParameter, ketQuaPictureParameter, scoreEyeParameter, ketQuaEyeParameter);
        }
    
        public virtual int ScoresUpdate(Nullable<System.Guid> id, string fullName, string birthday, Nullable<int> pI_P1, Nullable<int> pI_P2, Nullable<int> pI_P3, Nullable<int> pI_P4, Nullable<int> pI_P5, Nullable<int> pI_P6, Nullable<int> pI_P7, Nullable<int> pI_P8, Nullable<int> pI_P9, Nullable<int> pI_P10, Nullable<int> pI_P11, Nullable<int> pI_P12, Nullable<int> pI_P13, Nullable<int> pI_E1, Nullable<int> pI_E2, Nullable<int> pI_E3, Nullable<int> pI_E4, Nullable<int> pI_E5, Nullable<int> pI_E6, Nullable<int> pI_E7, Nullable<int> pI_E8, Nullable<int> pI_E9, Nullable<int> pI_E10, Nullable<int> pI_E11, Nullable<int> pI_E12, Nullable<int> pI_E13, Nullable<int> pII_P1, Nullable<int> pII_P2, Nullable<int> pII_P3, Nullable<int> pII_P4, Nullable<int> pII_P5, Nullable<int> pII_P6, Nullable<int> pII_P7, Nullable<int> pII_P8, Nullable<int> pII_P9, Nullable<int> pII_P10, Nullable<int> pII_P11, Nullable<int> pII_P12, Nullable<int> pII_P13, Nullable<int> pII_E1, Nullable<int> pII_E2, Nullable<int> pII_E3, Nullable<int> pII_E4, Nullable<int> pII_E5, Nullable<int> pII_E6, Nullable<int> pII_E7, Nullable<int> pII_E8, Nullable<int> pII_E9, Nullable<int> pII_E10, Nullable<int> pII_E11, Nullable<int> pII_E12, Nullable<int> pII_E13, Nullable<int> pI_SumPear, Nullable<int> pI_SumEven, Nullable<int> pII_SumPear, Nullable<int> pII_SumEven, Nullable<int> totalPear, Nullable<int> totalEven, Nullable<int> percent, Nullable<int> difference, string ketQua, Nullable<int> scorePicture, Nullable<int> percentPicture, string ketQuaPicture, Nullable<int> scoreEye, string ketQuaEye)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var birthdayParameter = birthday != null ?
                new ObjectParameter("Birthday", birthday) :
                new ObjectParameter("Birthday", typeof(string));
    
            var pI_P1Parameter = pI_P1.HasValue ?
                new ObjectParameter("PI_P1", pI_P1) :
                new ObjectParameter("PI_P1", typeof(int));
    
            var pI_P2Parameter = pI_P2.HasValue ?
                new ObjectParameter("PI_P2", pI_P2) :
                new ObjectParameter("PI_P2", typeof(int));
    
            var pI_P3Parameter = pI_P3.HasValue ?
                new ObjectParameter("PI_P3", pI_P3) :
                new ObjectParameter("PI_P3", typeof(int));
    
            var pI_P4Parameter = pI_P4.HasValue ?
                new ObjectParameter("PI_P4", pI_P4) :
                new ObjectParameter("PI_P4", typeof(int));
    
            var pI_P5Parameter = pI_P5.HasValue ?
                new ObjectParameter("PI_P5", pI_P5) :
                new ObjectParameter("PI_P5", typeof(int));
    
            var pI_P6Parameter = pI_P6.HasValue ?
                new ObjectParameter("PI_P6", pI_P6) :
                new ObjectParameter("PI_P6", typeof(int));
    
            var pI_P7Parameter = pI_P7.HasValue ?
                new ObjectParameter("PI_P7", pI_P7) :
                new ObjectParameter("PI_P7", typeof(int));
    
            var pI_P8Parameter = pI_P8.HasValue ?
                new ObjectParameter("PI_P8", pI_P8) :
                new ObjectParameter("PI_P8", typeof(int));
    
            var pI_P9Parameter = pI_P9.HasValue ?
                new ObjectParameter("PI_P9", pI_P9) :
                new ObjectParameter("PI_P9", typeof(int));
    
            var pI_P10Parameter = pI_P10.HasValue ?
                new ObjectParameter("PI_P10", pI_P10) :
                new ObjectParameter("PI_P10", typeof(int));
    
            var pI_P11Parameter = pI_P11.HasValue ?
                new ObjectParameter("PI_P11", pI_P11) :
                new ObjectParameter("PI_P11", typeof(int));
    
            var pI_P12Parameter = pI_P12.HasValue ?
                new ObjectParameter("PI_P12", pI_P12) :
                new ObjectParameter("PI_P12", typeof(int));
    
            var pI_P13Parameter = pI_P13.HasValue ?
                new ObjectParameter("PI_P13", pI_P13) :
                new ObjectParameter("PI_P13", typeof(int));
    
            var pI_E1Parameter = pI_E1.HasValue ?
                new ObjectParameter("PI_E1", pI_E1) :
                new ObjectParameter("PI_E1", typeof(int));
    
            var pI_E2Parameter = pI_E2.HasValue ?
                new ObjectParameter("PI_E2", pI_E2) :
                new ObjectParameter("PI_E2", typeof(int));
    
            var pI_E3Parameter = pI_E3.HasValue ?
                new ObjectParameter("PI_E3", pI_E3) :
                new ObjectParameter("PI_E3", typeof(int));
    
            var pI_E4Parameter = pI_E4.HasValue ?
                new ObjectParameter("PI_E4", pI_E4) :
                new ObjectParameter("PI_E4", typeof(int));
    
            var pI_E5Parameter = pI_E5.HasValue ?
                new ObjectParameter("PI_E5", pI_E5) :
                new ObjectParameter("PI_E5", typeof(int));
    
            var pI_E6Parameter = pI_E6.HasValue ?
                new ObjectParameter("PI_E6", pI_E6) :
                new ObjectParameter("PI_E6", typeof(int));
    
            var pI_E7Parameter = pI_E7.HasValue ?
                new ObjectParameter("PI_E7", pI_E7) :
                new ObjectParameter("PI_E7", typeof(int));
    
            var pI_E8Parameter = pI_E8.HasValue ?
                new ObjectParameter("PI_E8", pI_E8) :
                new ObjectParameter("PI_E8", typeof(int));
    
            var pI_E9Parameter = pI_E9.HasValue ?
                new ObjectParameter("PI_E9", pI_E9) :
                new ObjectParameter("PI_E9", typeof(int));
    
            var pI_E10Parameter = pI_E10.HasValue ?
                new ObjectParameter("PI_E10", pI_E10) :
                new ObjectParameter("PI_E10", typeof(int));
    
            var pI_E11Parameter = pI_E11.HasValue ?
                new ObjectParameter("PI_E11", pI_E11) :
                new ObjectParameter("PI_E11", typeof(int));
    
            var pI_E12Parameter = pI_E12.HasValue ?
                new ObjectParameter("PI_E12", pI_E12) :
                new ObjectParameter("PI_E12", typeof(int));
    
            var pI_E13Parameter = pI_E13.HasValue ?
                new ObjectParameter("PI_E13", pI_E13) :
                new ObjectParameter("PI_E13", typeof(int));
    
            var pII_P1Parameter = pII_P1.HasValue ?
                new ObjectParameter("PII_P1", pII_P1) :
                new ObjectParameter("PII_P1", typeof(int));
    
            var pII_P2Parameter = pII_P2.HasValue ?
                new ObjectParameter("PII_P2", pII_P2) :
                new ObjectParameter("PII_P2", typeof(int));
    
            var pII_P3Parameter = pII_P3.HasValue ?
                new ObjectParameter("PII_P3", pII_P3) :
                new ObjectParameter("PII_P3", typeof(int));
    
            var pII_P4Parameter = pII_P4.HasValue ?
                new ObjectParameter("PII_P4", pII_P4) :
                new ObjectParameter("PII_P4", typeof(int));
    
            var pII_P5Parameter = pII_P5.HasValue ?
                new ObjectParameter("PII_P5", pII_P5) :
                new ObjectParameter("PII_P5", typeof(int));
    
            var pII_P6Parameter = pII_P6.HasValue ?
                new ObjectParameter("PII_P6", pII_P6) :
                new ObjectParameter("PII_P6", typeof(int));
    
            var pII_P7Parameter = pII_P7.HasValue ?
                new ObjectParameter("PII_P7", pII_P7) :
                new ObjectParameter("PII_P7", typeof(int));
    
            var pII_P8Parameter = pII_P8.HasValue ?
                new ObjectParameter("PII_P8", pII_P8) :
                new ObjectParameter("PII_P8", typeof(int));
    
            var pII_P9Parameter = pII_P9.HasValue ?
                new ObjectParameter("PII_P9", pII_P9) :
                new ObjectParameter("PII_P9", typeof(int));
    
            var pII_P10Parameter = pII_P10.HasValue ?
                new ObjectParameter("PII_P10", pII_P10) :
                new ObjectParameter("PII_P10", typeof(int));
    
            var pII_P11Parameter = pII_P11.HasValue ?
                new ObjectParameter("PII_P11", pII_P11) :
                new ObjectParameter("PII_P11", typeof(int));
    
            var pII_P12Parameter = pII_P12.HasValue ?
                new ObjectParameter("PII_P12", pII_P12) :
                new ObjectParameter("PII_P12", typeof(int));
    
            var pII_P13Parameter = pII_P13.HasValue ?
                new ObjectParameter("PII_P13", pII_P13) :
                new ObjectParameter("PII_P13", typeof(int));
    
            var pII_E1Parameter = pII_E1.HasValue ?
                new ObjectParameter("PII_E1", pII_E1) :
                new ObjectParameter("PII_E1", typeof(int));
    
            var pII_E2Parameter = pII_E2.HasValue ?
                new ObjectParameter("PII_E2", pII_E2) :
                new ObjectParameter("PII_E2", typeof(int));
    
            var pII_E3Parameter = pII_E3.HasValue ?
                new ObjectParameter("PII_E3", pII_E3) :
                new ObjectParameter("PII_E3", typeof(int));
    
            var pII_E4Parameter = pII_E4.HasValue ?
                new ObjectParameter("PII_E4", pII_E4) :
                new ObjectParameter("PII_E4", typeof(int));
    
            var pII_E5Parameter = pII_E5.HasValue ?
                new ObjectParameter("PII_E5", pII_E5) :
                new ObjectParameter("PII_E5", typeof(int));
    
            var pII_E6Parameter = pII_E6.HasValue ?
                new ObjectParameter("PII_E6", pII_E6) :
                new ObjectParameter("PII_E6", typeof(int));
    
            var pII_E7Parameter = pII_E7.HasValue ?
                new ObjectParameter("PII_E7", pII_E7) :
                new ObjectParameter("PII_E7", typeof(int));
    
            var pII_E8Parameter = pII_E8.HasValue ?
                new ObjectParameter("PII_E8", pII_E8) :
                new ObjectParameter("PII_E8", typeof(int));
    
            var pII_E9Parameter = pII_E9.HasValue ?
                new ObjectParameter("PII_E9", pII_E9) :
                new ObjectParameter("PII_E9", typeof(int));
    
            var pII_E10Parameter = pII_E10.HasValue ?
                new ObjectParameter("PII_E10", pII_E10) :
                new ObjectParameter("PII_E10", typeof(int));
    
            var pII_E11Parameter = pII_E11.HasValue ?
                new ObjectParameter("PII_E11", pII_E11) :
                new ObjectParameter("PII_E11", typeof(int));
    
            var pII_E12Parameter = pII_E12.HasValue ?
                new ObjectParameter("PII_E12", pII_E12) :
                new ObjectParameter("PII_E12", typeof(int));
    
            var pII_E13Parameter = pII_E13.HasValue ?
                new ObjectParameter("PII_E13", pII_E13) :
                new ObjectParameter("PII_E13", typeof(int));
    
            var pI_SumPearParameter = pI_SumPear.HasValue ?
                new ObjectParameter("PI_SumPear", pI_SumPear) :
                new ObjectParameter("PI_SumPear", typeof(int));
    
            var pI_SumEvenParameter = pI_SumEven.HasValue ?
                new ObjectParameter("PI_SumEven", pI_SumEven) :
                new ObjectParameter("PI_SumEven", typeof(int));
    
            var pII_SumPearParameter = pII_SumPear.HasValue ?
                new ObjectParameter("PII_SumPear", pII_SumPear) :
                new ObjectParameter("PII_SumPear", typeof(int));
    
            var pII_SumEvenParameter = pII_SumEven.HasValue ?
                new ObjectParameter("PII_SumEven", pII_SumEven) :
                new ObjectParameter("PII_SumEven", typeof(int));
    
            var totalPearParameter = totalPear.HasValue ?
                new ObjectParameter("TotalPear", totalPear) :
                new ObjectParameter("TotalPear", typeof(int));
    
            var totalEvenParameter = totalEven.HasValue ?
                new ObjectParameter("TotalEven", totalEven) :
                new ObjectParameter("TotalEven", typeof(int));
    
            var percentParameter = percent.HasValue ?
                new ObjectParameter("Percent", percent) :
                new ObjectParameter("Percent", typeof(int));
    
            var differenceParameter = difference.HasValue ?
                new ObjectParameter("Difference", difference) :
                new ObjectParameter("Difference", typeof(int));
    
            var ketQuaParameter = ketQua != null ?
                new ObjectParameter("KetQua", ketQua) :
                new ObjectParameter("KetQua", typeof(string));
    
            var scorePictureParameter = scorePicture.HasValue ?
                new ObjectParameter("ScorePicture", scorePicture) :
                new ObjectParameter("ScorePicture", typeof(int));
    
            var percentPictureParameter = percentPicture.HasValue ?
                new ObjectParameter("PercentPicture", percentPicture) :
                new ObjectParameter("PercentPicture", typeof(int));
    
            var ketQuaPictureParameter = ketQuaPicture != null ?
                new ObjectParameter("KetQuaPicture", ketQuaPicture) :
                new ObjectParameter("KetQuaPicture", typeof(string));
    
            var scoreEyeParameter = scoreEye.HasValue ?
                new ObjectParameter("ScoreEye", scoreEye) :
                new ObjectParameter("ScoreEye", typeof(int));
    
            var ketQuaEyeParameter = ketQuaEye != null ?
                new ObjectParameter("KetQuaEye", ketQuaEye) :
                new ObjectParameter("KetQuaEye", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ScoresUpdate", idParameter, fullNameParameter, birthdayParameter, pI_P1Parameter, pI_P2Parameter, pI_P3Parameter, pI_P4Parameter, pI_P5Parameter, pI_P6Parameter, pI_P7Parameter, pI_P8Parameter, pI_P9Parameter, pI_P10Parameter, pI_P11Parameter, pI_P12Parameter, pI_P13Parameter, pI_E1Parameter, pI_E2Parameter, pI_E3Parameter, pI_E4Parameter, pI_E5Parameter, pI_E6Parameter, pI_E7Parameter, pI_E8Parameter, pI_E9Parameter, pI_E10Parameter, pI_E11Parameter, pI_E12Parameter, pI_E13Parameter, pII_P1Parameter, pII_P2Parameter, pII_P3Parameter, pII_P4Parameter, pII_P5Parameter, pII_P6Parameter, pII_P7Parameter, pII_P8Parameter, pII_P9Parameter, pII_P10Parameter, pII_P11Parameter, pII_P12Parameter, pII_P13Parameter, pII_E1Parameter, pII_E2Parameter, pII_E3Parameter, pII_E4Parameter, pII_E5Parameter, pII_E6Parameter, pII_E7Parameter, pII_E8Parameter, pII_E9Parameter, pII_E10Parameter, pII_E11Parameter, pII_E12Parameter, pII_E13Parameter, pI_SumPearParameter, pI_SumEvenParameter, pII_SumPearParameter, pII_SumEvenParameter, totalPearParameter, totalEvenParameter, percentParameter, differenceParameter, ketQuaParameter, scorePictureParameter, percentPictureParameter, ketQuaPictureParameter, scoreEyeParameter, ketQuaEyeParameter);
        }
    
        public virtual int UsersDelete(Nullable<int> userName)
        {
            var userNameParameter = userName.HasValue ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UsersDelete", userNameParameter);
        }
    
        public virtual int UsersInsert(string password, string fullName)
        {
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UsersInsert", passwordParameter, fullNameParameter);
        }
    
        public virtual ObjectResult<UsersSelect_Result> UsersSelect(Nullable<int> userName)
        {
            var userNameParameter = userName.HasValue ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsersSelect_Result>("UsersSelect", userNameParameter);
        }
    
        public virtual int UsersUpdate(string userName, string password, string fullName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UsersUpdate", userNameParameter, passwordParameter, fullNameParameter);
        }
    
        public virtual ObjectResult<sp_CheckLogin_Result> sp_CheckLogin(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CheckLogin_Result>("sp_CheckLogin", userNameParameter, passwordParameter);
        }
    
        public virtual int sp_DeleteScores(Nullable<System.Guid> id, Nullable<System.DateTime> dateCreated)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            var dateCreatedParameter = dateCreated.HasValue ?
                new ObjectParameter("DateCreated", dateCreated) :
                new ObjectParameter("DateCreated", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteScores", idParameter, dateCreatedParameter);
        }
    
        public virtual ObjectResult<sp_GetResultByCMT_Result> sp_GetResultByCMT(string cMT)
        {
            var cMTParameter = cMT != null ?
                new ObjectParameter("CMT", cMT) :
                new ObjectParameter("CMT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetResultByCMT_Result>("sp_GetResultByCMT", cMTParameter);
        }
    
        public virtual ObjectResult<sp_GetResultById_Result> sp_GetResultById(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetResultById_Result>("sp_GetResultById", idParameter);
        }
    
        public virtual ObjectResult<sp_GetResults_Result> sp_GetResults()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetResults_Result>("sp_GetResults");
        }
    
        public virtual ObjectResult<sp_GetScoreById_Result> sp_GetScoreById(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetScoreById_Result>("sp_GetScoreById", idParameter);
        }
    
        public virtual ObjectResult<sp_GetScores_Result> sp_GetScores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetScores_Result>("sp_GetScores");
        }
    
        public virtual ObjectResult<sp_GetScoresById_Result> sp_GetScoresById(Nullable<System.Guid> id, Nullable<System.DateTime> dateCreated)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            var dateCreatedParameter = dateCreated.HasValue ?
                new ObjectParameter("DateCreated", dateCreated) :
                new ObjectParameter("DateCreated", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetScoresById_Result>("sp_GetScoresById", idParameter, dateCreatedParameter);
        }
    
        public virtual ObjectResult<sp_GetUserByUserName_Result> sp_GetUserByUserName(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetUserByUserName_Result>("sp_GetUserByUserName", userNameParameter);
        }
    
        public virtual int sp_Insert_Results(string id, string fullName, Nullable<System.DateTime> birthday, string sex, string phoneNumber, string nS, string hKTT, string dT, string hight, string cMT, Nullable<System.DateTime> ngayCap, string noiCap, string experiene, string staffID, string staffCode, string dept, string position, Nullable<System.DateTime> ngayPV, string nguoiPV, Nullable<System.DateTime> ngayDiLam, string createdBy, Nullable<System.DateTime> createdDate)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var birthdayParameter = birthday.HasValue ?
                new ObjectParameter("Birthday", birthday) :
                new ObjectParameter("Birthday", typeof(System.DateTime));
    
            var sexParameter = sex != null ?
                new ObjectParameter("Sex", sex) :
                new ObjectParameter("Sex", typeof(string));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            var nSParameter = nS != null ?
                new ObjectParameter("NS", nS) :
                new ObjectParameter("NS", typeof(string));
    
            var hKTTParameter = hKTT != null ?
                new ObjectParameter("HKTT", hKTT) :
                new ObjectParameter("HKTT", typeof(string));
    
            var dTParameter = dT != null ?
                new ObjectParameter("DT", dT) :
                new ObjectParameter("DT", typeof(string));
    
            var hightParameter = hight != null ?
                new ObjectParameter("Hight", hight) :
                new ObjectParameter("Hight", typeof(string));
    
            var cMTParameter = cMT != null ?
                new ObjectParameter("CMT", cMT) :
                new ObjectParameter("CMT", typeof(string));
    
            var ngayCapParameter = ngayCap.HasValue ?
                new ObjectParameter("NgayCap", ngayCap) :
                new ObjectParameter("NgayCap", typeof(System.DateTime));
    
            var noiCapParameter = noiCap != null ?
                new ObjectParameter("NoiCap", noiCap) :
                new ObjectParameter("NoiCap", typeof(string));
    
            var experieneParameter = experiene != null ?
                new ObjectParameter("Experiene", experiene) :
                new ObjectParameter("Experiene", typeof(string));
    
            var staffIDParameter = staffID != null ?
                new ObjectParameter("StaffID", staffID) :
                new ObjectParameter("StaffID", typeof(string));
    
            var staffCodeParameter = staffCode != null ?
                new ObjectParameter("StaffCode", staffCode) :
                new ObjectParameter("StaffCode", typeof(string));
    
            var deptParameter = dept != null ?
                new ObjectParameter("Dept", dept) :
                new ObjectParameter("Dept", typeof(string));
    
            var positionParameter = position != null ?
                new ObjectParameter("Position", position) :
                new ObjectParameter("Position", typeof(string));
    
            var ngayPVParameter = ngayPV.HasValue ?
                new ObjectParameter("NgayPV", ngayPV) :
                new ObjectParameter("NgayPV", typeof(System.DateTime));
    
            var nguoiPVParameter = nguoiPV != null ?
                new ObjectParameter("NguoiPV", nguoiPV) :
                new ObjectParameter("NguoiPV", typeof(string));
    
            var ngayDiLamParameter = ngayDiLam.HasValue ?
                new ObjectParameter("NgayDiLam", ngayDiLam) :
                new ObjectParameter("NgayDiLam", typeof(System.DateTime));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var createdDateParameter = createdDate.HasValue ?
                new ObjectParameter("CreatedDate", createdDate) :
                new ObjectParameter("CreatedDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_Results", idParameter, fullNameParameter, birthdayParameter, sexParameter, phoneNumberParameter, nSParameter, hKTTParameter, dTParameter, hightParameter, cMTParameter, ngayCapParameter, noiCapParameter, experieneParameter, staffIDParameter, staffCodeParameter, deptParameter, positionParameter, ngayPVParameter, nguoiPVParameter, ngayDiLamParameter, createdByParameter, createdDateParameter);
        }
    
        public virtual int sp_InsertScores(Nullable<System.Guid> id, Nullable<System.DateTime> dateCreated, string fullName, string birthday, Nullable<int> pI_P1, Nullable<int> pI_P2, Nullable<int> pI_P3, Nullable<int> pI_P4, Nullable<int> pI_P5, Nullable<int> pI_P6, Nullable<int> pI_P7, Nullable<int> pI_P8, Nullable<int> pI_P9, Nullable<int> pI_P10, Nullable<int> pI_P11, Nullable<int> pI_P12, Nullable<int> pI_P13, Nullable<int> pI_E1, Nullable<int> pI_E2, Nullable<int> pI_E3, Nullable<int> pI_E4, Nullable<int> pI_E5, Nullable<int> pI_E6, Nullable<int> pI_E7, Nullable<int> pI_E8, Nullable<int> pI_E9, Nullable<int> pI_E10, Nullable<int> pI_E11, Nullable<int> pI_E12, Nullable<int> pI_E13, Nullable<int> pII_P1, Nullable<int> pII_P2, Nullable<int> pII_P3, Nullable<int> pII_P4, Nullable<int> pII_P5, Nullable<int> pII_P6, Nullable<int> pII_P7, Nullable<int> pII_P8, Nullable<int> pII_P9, Nullable<int> pII_P10, Nullable<int> pII_P11, Nullable<int> pII_P12, Nullable<int> pII_P13, Nullable<int> pII_E1, Nullable<int> pII_E2, Nullable<int> pII_E3, Nullable<int> pII_E4, Nullable<int> pII_E5, Nullable<int> pII_E6, Nullable<int> pII_E7, Nullable<int> pII_E8, Nullable<int> pII_E9, Nullable<int> pII_E10, Nullable<int> pII_E11, Nullable<int> pII_E12, Nullable<int> pII_E13, Nullable<int> pI_SumPear, Nullable<int> pI_SumEven, Nullable<int> pII_SumPear, Nullable<int> pII_SumEven, Nullable<int> totalPear, Nullable<int> totalEven, Nullable<int> percent, Nullable<int> difference, string ketQua, Nullable<int> scorePicture, Nullable<int> percentPicture, string ketQuaPicture, Nullable<int> scoreEye, string ketQuaEye)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            var dateCreatedParameter = dateCreated.HasValue ?
                new ObjectParameter("DateCreated", dateCreated) :
                new ObjectParameter("DateCreated", typeof(System.DateTime));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var birthdayParameter = birthday != null ?
                new ObjectParameter("Birthday", birthday) :
                new ObjectParameter("Birthday", typeof(string));
    
            var pI_P1Parameter = pI_P1.HasValue ?
                new ObjectParameter("PI_P1", pI_P1) :
                new ObjectParameter("PI_P1", typeof(int));
    
            var pI_P2Parameter = pI_P2.HasValue ?
                new ObjectParameter("PI_P2", pI_P2) :
                new ObjectParameter("PI_P2", typeof(int));
    
            var pI_P3Parameter = pI_P3.HasValue ?
                new ObjectParameter("PI_P3", pI_P3) :
                new ObjectParameter("PI_P3", typeof(int));
    
            var pI_P4Parameter = pI_P4.HasValue ?
                new ObjectParameter("PI_P4", pI_P4) :
                new ObjectParameter("PI_P4", typeof(int));
    
            var pI_P5Parameter = pI_P5.HasValue ?
                new ObjectParameter("PI_P5", pI_P5) :
                new ObjectParameter("PI_P5", typeof(int));
    
            var pI_P6Parameter = pI_P6.HasValue ?
                new ObjectParameter("PI_P6", pI_P6) :
                new ObjectParameter("PI_P6", typeof(int));
    
            var pI_P7Parameter = pI_P7.HasValue ?
                new ObjectParameter("PI_P7", pI_P7) :
                new ObjectParameter("PI_P7", typeof(int));
    
            var pI_P8Parameter = pI_P8.HasValue ?
                new ObjectParameter("PI_P8", pI_P8) :
                new ObjectParameter("PI_P8", typeof(int));
    
            var pI_P9Parameter = pI_P9.HasValue ?
                new ObjectParameter("PI_P9", pI_P9) :
                new ObjectParameter("PI_P9", typeof(int));
    
            var pI_P10Parameter = pI_P10.HasValue ?
                new ObjectParameter("PI_P10", pI_P10) :
                new ObjectParameter("PI_P10", typeof(int));
    
            var pI_P11Parameter = pI_P11.HasValue ?
                new ObjectParameter("PI_P11", pI_P11) :
                new ObjectParameter("PI_P11", typeof(int));
    
            var pI_P12Parameter = pI_P12.HasValue ?
                new ObjectParameter("PI_P12", pI_P12) :
                new ObjectParameter("PI_P12", typeof(int));
    
            var pI_P13Parameter = pI_P13.HasValue ?
                new ObjectParameter("PI_P13", pI_P13) :
                new ObjectParameter("PI_P13", typeof(int));
    
            var pI_E1Parameter = pI_E1.HasValue ?
                new ObjectParameter("PI_E1", pI_E1) :
                new ObjectParameter("PI_E1", typeof(int));
    
            var pI_E2Parameter = pI_E2.HasValue ?
                new ObjectParameter("PI_E2", pI_E2) :
                new ObjectParameter("PI_E2", typeof(int));
    
            var pI_E3Parameter = pI_E3.HasValue ?
                new ObjectParameter("PI_E3", pI_E3) :
                new ObjectParameter("PI_E3", typeof(int));
    
            var pI_E4Parameter = pI_E4.HasValue ?
                new ObjectParameter("PI_E4", pI_E4) :
                new ObjectParameter("PI_E4", typeof(int));
    
            var pI_E5Parameter = pI_E5.HasValue ?
                new ObjectParameter("PI_E5", pI_E5) :
                new ObjectParameter("PI_E5", typeof(int));
    
            var pI_E6Parameter = pI_E6.HasValue ?
                new ObjectParameter("PI_E6", pI_E6) :
                new ObjectParameter("PI_E6", typeof(int));
    
            var pI_E7Parameter = pI_E7.HasValue ?
                new ObjectParameter("PI_E7", pI_E7) :
                new ObjectParameter("PI_E7", typeof(int));
    
            var pI_E8Parameter = pI_E8.HasValue ?
                new ObjectParameter("PI_E8", pI_E8) :
                new ObjectParameter("PI_E8", typeof(int));
    
            var pI_E9Parameter = pI_E9.HasValue ?
                new ObjectParameter("PI_E9", pI_E9) :
                new ObjectParameter("PI_E9", typeof(int));
    
            var pI_E10Parameter = pI_E10.HasValue ?
                new ObjectParameter("PI_E10", pI_E10) :
                new ObjectParameter("PI_E10", typeof(int));
    
            var pI_E11Parameter = pI_E11.HasValue ?
                new ObjectParameter("PI_E11", pI_E11) :
                new ObjectParameter("PI_E11", typeof(int));
    
            var pI_E12Parameter = pI_E12.HasValue ?
                new ObjectParameter("PI_E12", pI_E12) :
                new ObjectParameter("PI_E12", typeof(int));
    
            var pI_E13Parameter = pI_E13.HasValue ?
                new ObjectParameter("PI_E13", pI_E13) :
                new ObjectParameter("PI_E13", typeof(int));
    
            var pII_P1Parameter = pII_P1.HasValue ?
                new ObjectParameter("PII_P1", pII_P1) :
                new ObjectParameter("PII_P1", typeof(int));
    
            var pII_P2Parameter = pII_P2.HasValue ?
                new ObjectParameter("PII_P2", pII_P2) :
                new ObjectParameter("PII_P2", typeof(int));
    
            var pII_P3Parameter = pII_P3.HasValue ?
                new ObjectParameter("PII_P3", pII_P3) :
                new ObjectParameter("PII_P3", typeof(int));
    
            var pII_P4Parameter = pII_P4.HasValue ?
                new ObjectParameter("PII_P4", pII_P4) :
                new ObjectParameter("PII_P4", typeof(int));
    
            var pII_P5Parameter = pII_P5.HasValue ?
                new ObjectParameter("PII_P5", pII_P5) :
                new ObjectParameter("PII_P5", typeof(int));
    
            var pII_P6Parameter = pII_P6.HasValue ?
                new ObjectParameter("PII_P6", pII_P6) :
                new ObjectParameter("PII_P6", typeof(int));
    
            var pII_P7Parameter = pII_P7.HasValue ?
                new ObjectParameter("PII_P7", pII_P7) :
                new ObjectParameter("PII_P7", typeof(int));
    
            var pII_P8Parameter = pII_P8.HasValue ?
                new ObjectParameter("PII_P8", pII_P8) :
                new ObjectParameter("PII_P8", typeof(int));
    
            var pII_P9Parameter = pII_P9.HasValue ?
                new ObjectParameter("PII_P9", pII_P9) :
                new ObjectParameter("PII_P9", typeof(int));
    
            var pII_P10Parameter = pII_P10.HasValue ?
                new ObjectParameter("PII_P10", pII_P10) :
                new ObjectParameter("PII_P10", typeof(int));
    
            var pII_P11Parameter = pII_P11.HasValue ?
                new ObjectParameter("PII_P11", pII_P11) :
                new ObjectParameter("PII_P11", typeof(int));
    
            var pII_P12Parameter = pII_P12.HasValue ?
                new ObjectParameter("PII_P12", pII_P12) :
                new ObjectParameter("PII_P12", typeof(int));
    
            var pII_P13Parameter = pII_P13.HasValue ?
                new ObjectParameter("PII_P13", pII_P13) :
                new ObjectParameter("PII_P13", typeof(int));
    
            var pII_E1Parameter = pII_E1.HasValue ?
                new ObjectParameter("PII_E1", pII_E1) :
                new ObjectParameter("PII_E1", typeof(int));
    
            var pII_E2Parameter = pII_E2.HasValue ?
                new ObjectParameter("PII_E2", pII_E2) :
                new ObjectParameter("PII_E2", typeof(int));
    
            var pII_E3Parameter = pII_E3.HasValue ?
                new ObjectParameter("PII_E3", pII_E3) :
                new ObjectParameter("PII_E3", typeof(int));
    
            var pII_E4Parameter = pII_E4.HasValue ?
                new ObjectParameter("PII_E4", pII_E4) :
                new ObjectParameter("PII_E4", typeof(int));
    
            var pII_E5Parameter = pII_E5.HasValue ?
                new ObjectParameter("PII_E5", pII_E5) :
                new ObjectParameter("PII_E5", typeof(int));
    
            var pII_E6Parameter = pII_E6.HasValue ?
                new ObjectParameter("PII_E6", pII_E6) :
                new ObjectParameter("PII_E6", typeof(int));
    
            var pII_E7Parameter = pII_E7.HasValue ?
                new ObjectParameter("PII_E7", pII_E7) :
                new ObjectParameter("PII_E7", typeof(int));
    
            var pII_E8Parameter = pII_E8.HasValue ?
                new ObjectParameter("PII_E8", pII_E8) :
                new ObjectParameter("PII_E8", typeof(int));
    
            var pII_E9Parameter = pII_E9.HasValue ?
                new ObjectParameter("PII_E9", pII_E9) :
                new ObjectParameter("PII_E9", typeof(int));
    
            var pII_E10Parameter = pII_E10.HasValue ?
                new ObjectParameter("PII_E10", pII_E10) :
                new ObjectParameter("PII_E10", typeof(int));
    
            var pII_E11Parameter = pII_E11.HasValue ?
                new ObjectParameter("PII_E11", pII_E11) :
                new ObjectParameter("PII_E11", typeof(int));
    
            var pII_E12Parameter = pII_E12.HasValue ?
                new ObjectParameter("PII_E12", pII_E12) :
                new ObjectParameter("PII_E12", typeof(int));
    
            var pII_E13Parameter = pII_E13.HasValue ?
                new ObjectParameter("PII_E13", pII_E13) :
                new ObjectParameter("PII_E13", typeof(int));
    
            var pI_SumPearParameter = pI_SumPear.HasValue ?
                new ObjectParameter("PI_SumPear", pI_SumPear) :
                new ObjectParameter("PI_SumPear", typeof(int));
    
            var pI_SumEvenParameter = pI_SumEven.HasValue ?
                new ObjectParameter("PI_SumEven", pI_SumEven) :
                new ObjectParameter("PI_SumEven", typeof(int));
    
            var pII_SumPearParameter = pII_SumPear.HasValue ?
                new ObjectParameter("PII_SumPear", pII_SumPear) :
                new ObjectParameter("PII_SumPear", typeof(int));
    
            var pII_SumEvenParameter = pII_SumEven.HasValue ?
                new ObjectParameter("PII_SumEven", pII_SumEven) :
                new ObjectParameter("PII_SumEven", typeof(int));
    
            var totalPearParameter = totalPear.HasValue ?
                new ObjectParameter("TotalPear", totalPear) :
                new ObjectParameter("TotalPear", typeof(int));
    
            var totalEvenParameter = totalEven.HasValue ?
                new ObjectParameter("TotalEven", totalEven) :
                new ObjectParameter("TotalEven", typeof(int));
    
            var percentParameter = percent.HasValue ?
                new ObjectParameter("Percent", percent) :
                new ObjectParameter("Percent", typeof(int));
    
            var differenceParameter = difference.HasValue ?
                new ObjectParameter("Difference", difference) :
                new ObjectParameter("Difference", typeof(int));
    
            var ketQuaParameter = ketQua != null ?
                new ObjectParameter("KetQua", ketQua) :
                new ObjectParameter("KetQua", typeof(string));
    
            var scorePictureParameter = scorePicture.HasValue ?
                new ObjectParameter("ScorePicture", scorePicture) :
                new ObjectParameter("ScorePicture", typeof(int));
    
            var percentPictureParameter = percentPicture.HasValue ?
                new ObjectParameter("PercentPicture", percentPicture) :
                new ObjectParameter("PercentPicture", typeof(int));
    
            var ketQuaPictureParameter = ketQuaPicture != null ?
                new ObjectParameter("KetQuaPicture", ketQuaPicture) :
                new ObjectParameter("KetQuaPicture", typeof(string));
    
            var scoreEyeParameter = scoreEye.HasValue ?
                new ObjectParameter("ScoreEye", scoreEye) :
                new ObjectParameter("ScoreEye", typeof(int));
    
            var ketQuaEyeParameter = ketQuaEye != null ?
                new ObjectParameter("KetQuaEye", ketQuaEye) :
                new ObjectParameter("KetQuaEye", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertScores", idParameter, dateCreatedParameter, fullNameParameter, birthdayParameter, pI_P1Parameter, pI_P2Parameter, pI_P3Parameter, pI_P4Parameter, pI_P5Parameter, pI_P6Parameter, pI_P7Parameter, pI_P8Parameter, pI_P9Parameter, pI_P10Parameter, pI_P11Parameter, pI_P12Parameter, pI_P13Parameter, pI_E1Parameter, pI_E2Parameter, pI_E3Parameter, pI_E4Parameter, pI_E5Parameter, pI_E6Parameter, pI_E7Parameter, pI_E8Parameter, pI_E9Parameter, pI_E10Parameter, pI_E11Parameter, pI_E12Parameter, pI_E13Parameter, pII_P1Parameter, pII_P2Parameter, pII_P3Parameter, pII_P4Parameter, pII_P5Parameter, pII_P6Parameter, pII_P7Parameter, pII_P8Parameter, pII_P9Parameter, pII_P10Parameter, pII_P11Parameter, pII_P12Parameter, pII_P13Parameter, pII_E1Parameter, pII_E2Parameter, pII_E3Parameter, pII_E4Parameter, pII_E5Parameter, pII_E6Parameter, pII_E7Parameter, pII_E8Parameter, pII_E9Parameter, pII_E10Parameter, pII_E11Parameter, pII_E12Parameter, pII_E13Parameter, pI_SumPearParameter, pI_SumEvenParameter, pII_SumPearParameter, pII_SumEvenParameter, totalPearParameter, totalEvenParameter, percentParameter, differenceParameter, ketQuaParameter, scorePictureParameter, percentPictureParameter, ketQuaPictureParameter, scoreEyeParameter, ketQuaEyeParameter);
        }
    
        public virtual int sp_Update_Results(string id, string fullName, Nullable<System.DateTime> birthday, string sex, string phoneNumber, string nS, string hKTT, string dT, string hight, string cMT, Nullable<System.DateTime> ngayCap, string noiCap, string experiene, string staffID, string staffCode, string dept, string position, Nullable<System.DateTime> ngayPV, string nguoiPV, Nullable<System.DateTime> ngayDiLam, string modifyBy, Nullable<System.DateTime> modifyDate)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var birthdayParameter = birthday.HasValue ?
                new ObjectParameter("Birthday", birthday) :
                new ObjectParameter("Birthday", typeof(System.DateTime));
    
            var sexParameter = sex != null ?
                new ObjectParameter("Sex", sex) :
                new ObjectParameter("Sex", typeof(string));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            var nSParameter = nS != null ?
                new ObjectParameter("NS", nS) :
                new ObjectParameter("NS", typeof(string));
    
            var hKTTParameter = hKTT != null ?
                new ObjectParameter("HKTT", hKTT) :
                new ObjectParameter("HKTT", typeof(string));
    
            var dTParameter = dT != null ?
                new ObjectParameter("DT", dT) :
                new ObjectParameter("DT", typeof(string));
    
            var hightParameter = hight != null ?
                new ObjectParameter("Hight", hight) :
                new ObjectParameter("Hight", typeof(string));
    
            var cMTParameter = cMT != null ?
                new ObjectParameter("CMT", cMT) :
                new ObjectParameter("CMT", typeof(string));
    
            var ngayCapParameter = ngayCap.HasValue ?
                new ObjectParameter("NgayCap", ngayCap) :
                new ObjectParameter("NgayCap", typeof(System.DateTime));
    
            var noiCapParameter = noiCap != null ?
                new ObjectParameter("NoiCap", noiCap) :
                new ObjectParameter("NoiCap", typeof(string));
    
            var experieneParameter = experiene != null ?
                new ObjectParameter("Experiene", experiene) :
                new ObjectParameter("Experiene", typeof(string));
    
            var staffIDParameter = staffID != null ?
                new ObjectParameter("StaffID", staffID) :
                new ObjectParameter("StaffID", typeof(string));
    
            var staffCodeParameter = staffCode != null ?
                new ObjectParameter("StaffCode", staffCode) :
                new ObjectParameter("StaffCode", typeof(string));
    
            var deptParameter = dept != null ?
                new ObjectParameter("Dept", dept) :
                new ObjectParameter("Dept", typeof(string));
    
            var positionParameter = position != null ?
                new ObjectParameter("Position", position) :
                new ObjectParameter("Position", typeof(string));
    
            var ngayPVParameter = ngayPV.HasValue ?
                new ObjectParameter("NgayPV", ngayPV) :
                new ObjectParameter("NgayPV", typeof(System.DateTime));
    
            var nguoiPVParameter = nguoiPV != null ?
                new ObjectParameter("NguoiPV", nguoiPV) :
                new ObjectParameter("NguoiPV", typeof(string));
    
            var ngayDiLamParameter = ngayDiLam.HasValue ?
                new ObjectParameter("NgayDiLam", ngayDiLam) :
                new ObjectParameter("NgayDiLam", typeof(System.DateTime));
    
            var modifyByParameter = modifyBy != null ?
                new ObjectParameter("ModifyBy", modifyBy) :
                new ObjectParameter("ModifyBy", typeof(string));
    
            var modifyDateParameter = modifyDate.HasValue ?
                new ObjectParameter("ModifyDate", modifyDate) :
                new ObjectParameter("ModifyDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Update_Results", idParameter, fullNameParameter, birthdayParameter, sexParameter, phoneNumberParameter, nSParameter, hKTTParameter, dTParameter, hightParameter, cMTParameter, ngayCapParameter, noiCapParameter, experieneParameter, staffIDParameter, staffCodeParameter, deptParameter, positionParameter, ngayPVParameter, nguoiPVParameter, ngayDiLamParameter, modifyByParameter, modifyDateParameter);
        }
    
        public virtual int sp_UpdateScores(Nullable<System.Guid> id, Nullable<System.DateTime> dateCreated, string fullName, string birthday, Nullable<int> pI_P1, Nullable<int> pI_P2, Nullable<int> pI_P3, Nullable<int> pI_P4, Nullable<int> pI_P5, Nullable<int> pI_P6, Nullable<int> pI_P7, Nullable<int> pI_P8, Nullable<int> pI_P9, Nullable<int> pI_P10, Nullable<int> pI_P11, Nullable<int> pI_P12, Nullable<int> pI_P13, Nullable<int> pI_E1, Nullable<int> pI_E2, Nullable<int> pI_E3, Nullable<int> pI_E4, Nullable<int> pI_E5, Nullable<int> pI_E6, Nullable<int> pI_E7, Nullable<int> pI_E8, Nullable<int> pI_E9, Nullable<int> pI_E10, Nullable<int> pI_E11, Nullable<int> pI_E12, Nullable<int> pI_E13, Nullable<int> pII_P1, Nullable<int> pII_P2, Nullable<int> pII_P3, Nullable<int> pII_P4, Nullable<int> pII_P5, Nullable<int> pII_P6, Nullable<int> pII_P7, Nullable<int> pII_P8, Nullable<int> pII_P9, Nullable<int> pII_P10, Nullable<int> pII_P11, Nullable<int> pII_P12, Nullable<int> pII_P13, Nullable<int> pII_E1, Nullable<int> pII_E2, Nullable<int> pII_E3, Nullable<int> pII_E4, Nullable<int> pII_E5, Nullable<int> pII_E6, Nullable<int> pII_E7, Nullable<int> pII_E8, Nullable<int> pII_E9, Nullable<int> pII_E10, Nullable<int> pII_E11, Nullable<int> pII_E12, Nullable<int> pII_E13, Nullable<int> pI_SumPear, Nullable<int> pI_SumEven, Nullable<int> pII_SumPear, Nullable<int> pII_SumEven, Nullable<int> totalPear, Nullable<int> totalEven, Nullable<int> percent, Nullable<int> difference, string ketQua, Nullable<int> scorePicture, Nullable<int> percentPicture, string ketQuaPicture, Nullable<int> scoreEye, string ketQuaEye)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            var dateCreatedParameter = dateCreated.HasValue ?
                new ObjectParameter("DateCreated", dateCreated) :
                new ObjectParameter("DateCreated", typeof(System.DateTime));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var birthdayParameter = birthday != null ?
                new ObjectParameter("Birthday", birthday) :
                new ObjectParameter("Birthday", typeof(string));
    
            var pI_P1Parameter = pI_P1.HasValue ?
                new ObjectParameter("PI_P1", pI_P1) :
                new ObjectParameter("PI_P1", typeof(int));
    
            var pI_P2Parameter = pI_P2.HasValue ?
                new ObjectParameter("PI_P2", pI_P2) :
                new ObjectParameter("PI_P2", typeof(int));
    
            var pI_P3Parameter = pI_P3.HasValue ?
                new ObjectParameter("PI_P3", pI_P3) :
                new ObjectParameter("PI_P3", typeof(int));
    
            var pI_P4Parameter = pI_P4.HasValue ?
                new ObjectParameter("PI_P4", pI_P4) :
                new ObjectParameter("PI_P4", typeof(int));
    
            var pI_P5Parameter = pI_P5.HasValue ?
                new ObjectParameter("PI_P5", pI_P5) :
                new ObjectParameter("PI_P5", typeof(int));
    
            var pI_P6Parameter = pI_P6.HasValue ?
                new ObjectParameter("PI_P6", pI_P6) :
                new ObjectParameter("PI_P6", typeof(int));
    
            var pI_P7Parameter = pI_P7.HasValue ?
                new ObjectParameter("PI_P7", pI_P7) :
                new ObjectParameter("PI_P7", typeof(int));
    
            var pI_P8Parameter = pI_P8.HasValue ?
                new ObjectParameter("PI_P8", pI_P8) :
                new ObjectParameter("PI_P8", typeof(int));
    
            var pI_P9Parameter = pI_P9.HasValue ?
                new ObjectParameter("PI_P9", pI_P9) :
                new ObjectParameter("PI_P9", typeof(int));
    
            var pI_P10Parameter = pI_P10.HasValue ?
                new ObjectParameter("PI_P10", pI_P10) :
                new ObjectParameter("PI_P10", typeof(int));
    
            var pI_P11Parameter = pI_P11.HasValue ?
                new ObjectParameter("PI_P11", pI_P11) :
                new ObjectParameter("PI_P11", typeof(int));
    
            var pI_P12Parameter = pI_P12.HasValue ?
                new ObjectParameter("PI_P12", pI_P12) :
                new ObjectParameter("PI_P12", typeof(int));
    
            var pI_P13Parameter = pI_P13.HasValue ?
                new ObjectParameter("PI_P13", pI_P13) :
                new ObjectParameter("PI_P13", typeof(int));
    
            var pI_E1Parameter = pI_E1.HasValue ?
                new ObjectParameter("PI_E1", pI_E1) :
                new ObjectParameter("PI_E1", typeof(int));
    
            var pI_E2Parameter = pI_E2.HasValue ?
                new ObjectParameter("PI_E2", pI_E2) :
                new ObjectParameter("PI_E2", typeof(int));
    
            var pI_E3Parameter = pI_E3.HasValue ?
                new ObjectParameter("PI_E3", pI_E3) :
                new ObjectParameter("PI_E3", typeof(int));
    
            var pI_E4Parameter = pI_E4.HasValue ?
                new ObjectParameter("PI_E4", pI_E4) :
                new ObjectParameter("PI_E4", typeof(int));
    
            var pI_E5Parameter = pI_E5.HasValue ?
                new ObjectParameter("PI_E5", pI_E5) :
                new ObjectParameter("PI_E5", typeof(int));
    
            var pI_E6Parameter = pI_E6.HasValue ?
                new ObjectParameter("PI_E6", pI_E6) :
                new ObjectParameter("PI_E6", typeof(int));
    
            var pI_E7Parameter = pI_E7.HasValue ?
                new ObjectParameter("PI_E7", pI_E7) :
                new ObjectParameter("PI_E7", typeof(int));
    
            var pI_E8Parameter = pI_E8.HasValue ?
                new ObjectParameter("PI_E8", pI_E8) :
                new ObjectParameter("PI_E8", typeof(int));
    
            var pI_E9Parameter = pI_E9.HasValue ?
                new ObjectParameter("PI_E9", pI_E9) :
                new ObjectParameter("PI_E9", typeof(int));
    
            var pI_E10Parameter = pI_E10.HasValue ?
                new ObjectParameter("PI_E10", pI_E10) :
                new ObjectParameter("PI_E10", typeof(int));
    
            var pI_E11Parameter = pI_E11.HasValue ?
                new ObjectParameter("PI_E11", pI_E11) :
                new ObjectParameter("PI_E11", typeof(int));
    
            var pI_E12Parameter = pI_E12.HasValue ?
                new ObjectParameter("PI_E12", pI_E12) :
                new ObjectParameter("PI_E12", typeof(int));
    
            var pI_E13Parameter = pI_E13.HasValue ?
                new ObjectParameter("PI_E13", pI_E13) :
                new ObjectParameter("PI_E13", typeof(int));
    
            var pII_P1Parameter = pII_P1.HasValue ?
                new ObjectParameter("PII_P1", pII_P1) :
                new ObjectParameter("PII_P1", typeof(int));
    
            var pII_P2Parameter = pII_P2.HasValue ?
                new ObjectParameter("PII_P2", pII_P2) :
                new ObjectParameter("PII_P2", typeof(int));
    
            var pII_P3Parameter = pII_P3.HasValue ?
                new ObjectParameter("PII_P3", pII_P3) :
                new ObjectParameter("PII_P3", typeof(int));
    
            var pII_P4Parameter = pII_P4.HasValue ?
                new ObjectParameter("PII_P4", pII_P4) :
                new ObjectParameter("PII_P4", typeof(int));
    
            var pII_P5Parameter = pII_P5.HasValue ?
                new ObjectParameter("PII_P5", pII_P5) :
                new ObjectParameter("PII_P5", typeof(int));
    
            var pII_P6Parameter = pII_P6.HasValue ?
                new ObjectParameter("PII_P6", pII_P6) :
                new ObjectParameter("PII_P6", typeof(int));
    
            var pII_P7Parameter = pII_P7.HasValue ?
                new ObjectParameter("PII_P7", pII_P7) :
                new ObjectParameter("PII_P7", typeof(int));
    
            var pII_P8Parameter = pII_P8.HasValue ?
                new ObjectParameter("PII_P8", pII_P8) :
                new ObjectParameter("PII_P8", typeof(int));
    
            var pII_P9Parameter = pII_P9.HasValue ?
                new ObjectParameter("PII_P9", pII_P9) :
                new ObjectParameter("PII_P9", typeof(int));
    
            var pII_P10Parameter = pII_P10.HasValue ?
                new ObjectParameter("PII_P10", pII_P10) :
                new ObjectParameter("PII_P10", typeof(int));
    
            var pII_P11Parameter = pII_P11.HasValue ?
                new ObjectParameter("PII_P11", pII_P11) :
                new ObjectParameter("PII_P11", typeof(int));
    
            var pII_P12Parameter = pII_P12.HasValue ?
                new ObjectParameter("PII_P12", pII_P12) :
                new ObjectParameter("PII_P12", typeof(int));
    
            var pII_P13Parameter = pII_P13.HasValue ?
                new ObjectParameter("PII_P13", pII_P13) :
                new ObjectParameter("PII_P13", typeof(int));
    
            var pII_E1Parameter = pII_E1.HasValue ?
                new ObjectParameter("PII_E1", pII_E1) :
                new ObjectParameter("PII_E1", typeof(int));
    
            var pII_E2Parameter = pII_E2.HasValue ?
                new ObjectParameter("PII_E2", pII_E2) :
                new ObjectParameter("PII_E2", typeof(int));
    
            var pII_E3Parameter = pII_E3.HasValue ?
                new ObjectParameter("PII_E3", pII_E3) :
                new ObjectParameter("PII_E3", typeof(int));
    
            var pII_E4Parameter = pII_E4.HasValue ?
                new ObjectParameter("PII_E4", pII_E4) :
                new ObjectParameter("PII_E4", typeof(int));
    
            var pII_E5Parameter = pII_E5.HasValue ?
                new ObjectParameter("PII_E5", pII_E5) :
                new ObjectParameter("PII_E5", typeof(int));
    
            var pII_E6Parameter = pII_E6.HasValue ?
                new ObjectParameter("PII_E6", pII_E6) :
                new ObjectParameter("PII_E6", typeof(int));
    
            var pII_E7Parameter = pII_E7.HasValue ?
                new ObjectParameter("PII_E7", pII_E7) :
                new ObjectParameter("PII_E7", typeof(int));
    
            var pII_E8Parameter = pII_E8.HasValue ?
                new ObjectParameter("PII_E8", pII_E8) :
                new ObjectParameter("PII_E8", typeof(int));
    
            var pII_E9Parameter = pII_E9.HasValue ?
                new ObjectParameter("PII_E9", pII_E9) :
                new ObjectParameter("PII_E9", typeof(int));
    
            var pII_E10Parameter = pII_E10.HasValue ?
                new ObjectParameter("PII_E10", pII_E10) :
                new ObjectParameter("PII_E10", typeof(int));
    
            var pII_E11Parameter = pII_E11.HasValue ?
                new ObjectParameter("PII_E11", pII_E11) :
                new ObjectParameter("PII_E11", typeof(int));
    
            var pII_E12Parameter = pII_E12.HasValue ?
                new ObjectParameter("PII_E12", pII_E12) :
                new ObjectParameter("PII_E12", typeof(int));
    
            var pII_E13Parameter = pII_E13.HasValue ?
                new ObjectParameter("PII_E13", pII_E13) :
                new ObjectParameter("PII_E13", typeof(int));
    
            var pI_SumPearParameter = pI_SumPear.HasValue ?
                new ObjectParameter("PI_SumPear", pI_SumPear) :
                new ObjectParameter("PI_SumPear", typeof(int));
    
            var pI_SumEvenParameter = pI_SumEven.HasValue ?
                new ObjectParameter("PI_SumEven", pI_SumEven) :
                new ObjectParameter("PI_SumEven", typeof(int));
    
            var pII_SumPearParameter = pII_SumPear.HasValue ?
                new ObjectParameter("PII_SumPear", pII_SumPear) :
                new ObjectParameter("PII_SumPear", typeof(int));
    
            var pII_SumEvenParameter = pII_SumEven.HasValue ?
                new ObjectParameter("PII_SumEven", pII_SumEven) :
                new ObjectParameter("PII_SumEven", typeof(int));
    
            var totalPearParameter = totalPear.HasValue ?
                new ObjectParameter("TotalPear", totalPear) :
                new ObjectParameter("TotalPear", typeof(int));
    
            var totalEvenParameter = totalEven.HasValue ?
                new ObjectParameter("TotalEven", totalEven) :
                new ObjectParameter("TotalEven", typeof(int));
    
            var percentParameter = percent.HasValue ?
                new ObjectParameter("Percent", percent) :
                new ObjectParameter("Percent", typeof(int));
    
            var differenceParameter = difference.HasValue ?
                new ObjectParameter("Difference", difference) :
                new ObjectParameter("Difference", typeof(int));
    
            var ketQuaParameter = ketQua != null ?
                new ObjectParameter("KetQua", ketQua) :
                new ObjectParameter("KetQua", typeof(string));
    
            var scorePictureParameter = scorePicture.HasValue ?
                new ObjectParameter("ScorePicture", scorePicture) :
                new ObjectParameter("ScorePicture", typeof(int));
    
            var percentPictureParameter = percentPicture.HasValue ?
                new ObjectParameter("PercentPicture", percentPicture) :
                new ObjectParameter("PercentPicture", typeof(int));
    
            var ketQuaPictureParameter = ketQuaPicture != null ?
                new ObjectParameter("KetQuaPicture", ketQuaPicture) :
                new ObjectParameter("KetQuaPicture", typeof(string));
    
            var scoreEyeParameter = scoreEye.HasValue ?
                new ObjectParameter("ScoreEye", scoreEye) :
                new ObjectParameter("ScoreEye", typeof(int));
    
            var ketQuaEyeParameter = ketQuaEye != null ?
                new ObjectParameter("KetQuaEye", ketQuaEye) :
                new ObjectParameter("KetQuaEye", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateScores", idParameter, dateCreatedParameter, fullNameParameter, birthdayParameter, pI_P1Parameter, pI_P2Parameter, pI_P3Parameter, pI_P4Parameter, pI_P5Parameter, pI_P6Parameter, pI_P7Parameter, pI_P8Parameter, pI_P9Parameter, pI_P10Parameter, pI_P11Parameter, pI_P12Parameter, pI_P13Parameter, pI_E1Parameter, pI_E2Parameter, pI_E3Parameter, pI_E4Parameter, pI_E5Parameter, pI_E6Parameter, pI_E7Parameter, pI_E8Parameter, pI_E9Parameter, pI_E10Parameter, pI_E11Parameter, pI_E12Parameter, pI_E13Parameter, pII_P1Parameter, pII_P2Parameter, pII_P3Parameter, pII_P4Parameter, pII_P5Parameter, pII_P6Parameter, pII_P7Parameter, pII_P8Parameter, pII_P9Parameter, pII_P10Parameter, pII_P11Parameter, pII_P12Parameter, pII_P13Parameter, pII_E1Parameter, pII_E2Parameter, pII_E3Parameter, pII_E4Parameter, pII_E5Parameter, pII_E6Parameter, pII_E7Parameter, pII_E8Parameter, pII_E9Parameter, pII_E10Parameter, pII_E11Parameter, pII_E12Parameter, pII_E13Parameter, pI_SumPearParameter, pI_SumEvenParameter, pII_SumPearParameter, pII_SumEvenParameter, totalPearParameter, totalEvenParameter, percentParameter, differenceParameter, ketQuaParameter, scorePictureParameter, percentPictureParameter, ketQuaPictureParameter, scoreEyeParameter, ketQuaEyeParameter);
        }
    }
}
