//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indicate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information_NG
    {
        public int Id { get; set; }
        public string Serial_NG { get; set; }
        public string Process_NG { get; set; }
        public string Comment_NG { get; set; }
        public Nullable<System.DateTime> Time_ng { get; set; }
        public string User_ng { get; set; }
    }
}
