//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indicate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Line_status
    {
        public string Id_customer { get; set; }
        public int Id_Line { get; set; }
        public string Current_model { get; set; }
        public Nullable<int> Shift { get; set; }
    }
}
