//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indicate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Line
    {
        public Line()
        {
            this.Lines_processes = new HashSet<Lines_processes>();
            this.Users_processes = new HashSet<Users_processes>();
            this.Models = new HashSet<Model>();
        }
    
        public int Id_line { get; set; }
        public string Name_line { get; set; }
        public string Id_customer { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Lines_processes> Lines_processes { get; set; }
        public virtual ICollection<Users_processes> Users_processes { get; set; }
        public virtual ICollection<Model> Models { get; set; }
    }
}
