//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indicate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public Model()
        {
            this.Lines = new HashSet<Line>();
        }
    
        public string Id_model { get; set; }
        public string Name_model { get; set; }
        public string Model_code { get; set; }
        public int Label_length { get; set; }
        public Nullable<int> Start_position_label { get; set; }
        public Nullable<int> Set_plan { get; set; }
    
        public virtual ICollection<Line> Lines { get; set; }
    }
}
