//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indicate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sheet_productions
    {
        public Sheet_productions()
        {
            this.Show_Result = new HashSet<Show_Result>();
            this.Timings = new HashSet<Timing>();
        }
    
        public int Id_sheet_production { get; set; }
        public string Name_sheet_production { get; set; }
    
        public virtual ICollection<Show_Result> Show_Result { get; set; }
        public virtual ICollection<Timing> Timings { get; set; }
    }
}
