//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indicate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Users_processes = new HashSet<Users_processes>();
        }
    
        public string Id_user { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public bool Setup_client { get; set; }
        public Nullable<bool> manage { get; set; }
    
        public virtual ICollection<Users_processes> Users_processes { get; set; }
    }
}
