//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indicate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_processes
    {
        public string Id_user { get; set; }
        public string Id_process { get; set; }
        public int Id_line { get; set; }
    
        public virtual All_Processes All_Processes { get; set; }
        public virtual Line Line { get; set; }
        public virtual User User { get; set; }
    }
}
