//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public string ProductID { get; set; }
        public string Date { get; set; }
        public string ReceiptID { get; set; }
        public string IssueID { get; set; }
        public System.DateTime InventoryDate { get; set; }
        public Nullable<int> InventoryFirt { get; set; }
        public Nullable<int> Plan { get; set; }
        public Nullable<int> TotalIn { get; set; }
        public Nullable<int> TotalOut { get; set; }
        public Nullable<int> InventoryLast { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
