//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Users = new HashSet<User>();
        }
    
        public string ItemID { get; set; }
        public string ItemName { get; set; }
        public int Position { get; set; }
        public bool Visible { get; set; }
        public string PageID { get; set; }
        public string PageGroup { get; set; }
    
        public virtual Page Page { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
