//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public System.Guid ID { get; set; }
        public string Username { get; set; }
        public string FullName { get; set; }
        public System.DateTime LogDate { get; set; }
        public string Action { get; set; }
        public string Form { get; set; }
        public string IP { get; set; }
        public string MacAddress { get; set; }
        public string ComputerName { get; set; }
    }
}
