//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public Page()
        {
            this.Items = new HashSet<Item>();
        }
    
        public string PageID { get; set; }
        public string PageName { get; set; }
        public int Position { get; set; }
        public bool Visible { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
    }
}
