//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public Permission()
        {
            this.UserPermissions = new HashSet<UserPermission>();
        }
    
        public string ObjectID { get; set; }
        public string ObjectName { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public int Position { get; set; }
        public int RoleID { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual ICollection<UserPermission> UserPermissions { get; set; }
    }
}
