//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public Receipt()
        {
            this.ReceiptDetails = new HashSet<ReceiptDetail>();
        }
    
        public string ReceiptID { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public string Status { get; set; }
        public bool Active { get; set; }
        public string Note { get; set; }
        public Nullable<long> Price { get; set; }
        public Nullable<long> TotalMoney { get; set; }
        public string Supplier { get; set; }
        public string CreateBy { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> Plan { get; set; }
    
        public virtual ICollection<ReceiptDetail> ReceiptDetails { get; set; }
    }
}
