//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserPermissions = new HashSet<UserPermission>();
            this.Items = new HashSet<Item>();
        }
    
        public string Username { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public bool IsActive { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
    
        public virtual ICollection<UserPermission> UserPermissions { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}
