//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeekReport
    {
        public string DepartmentID { get; set; }
        public string ReportDate { get; set; }
        public Nullable<int> Week_1 { get; set; }
        public Nullable<int> Week_2 { get; set; }
        public Nullable<int> Week_3 { get; set; }
        public Nullable<int> Week_4 { get; set; }
        public Nullable<int> Week_5 { get; set; }
        public Nullable<int> TOTAL { get; set; }
        public string DepartmentName { get; set; }
    }
}
