//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePurchase.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string CUST_CODE { get; set; }
        public string CUST_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string CODE_TAX { get; set; }
        public string TEL { get; set; }
        public string FAX { get; set; }
        public string NAME_PART { get; set; }
        public string NAME_CUS { get; set; }
        public string PAY_TYPE { get; set; }
        public string PAY_TERM { get; set; }
        public string CURRENCY { get; set; }
        public string TAX_CODE { get; set; }
        public string DEL_TERM { get; set; }
        public string DEL_PLACE { get; set; }
        public string BUYER { get; set; }
        public string NAME_PART1 { get; set; }
    }
}
