//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartonLabel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Label
    {
        public string CreatedDate { get; set; }
        public string DeliveryDate { get; set; }
        public string FinalConsignee { get; set; }
        public string Supplier { get; set; }
        public string PoNo { get; set; }
        public string GrossWeight { get; set; }
        public string BoxQuantity { get; set; }
        public string POQuantity { get; set; }
        public string PartNo { get; set; }
        public string CNO { get; set; }
        public string ManufactureDate { get; set; }
        public int ID { get; set; }
    }
}
