//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartonLabel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public string PartNoID { get; set; }
        public string PartNoValue { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<long> Price { get; set; }
        public string Description { get; set; }
        public Nullable<double> Weight { get; set; }
    }
}
