//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock.GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stock.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn thoát không?.
        /// </summary>
        internal static string MessageBoxColseForm {
            get {
                return ResourceManager.GetString("MessageBoxColseForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không được bỏ trống !.
        /// </summary>
        internal static string MessageBoxPasswordNotNull {
            get {
                return ResourceManager.GetString("MessageBoxPasswordNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THÔNG BÁO.
        /// </summary>
        internal static string MessageBoxTitle {
            get {
                return ResourceManager.GetString("MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn chưa được kích hoạt. Vui lòng liên hệ với quản trị để được hỗ trợ!.
        /// </summary>
        internal static string MessageBoxUsernameNotActive {
            get {
                return ResourceManager.GetString("MessageBoxUsernameNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản {0} của bạn không tồn tại!.
        /// </summary>
        internal static string MessageBoxUsernameNotExits {
            get {
                return ResourceManager.GetString("MessageBoxUsernameNotExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập không được bỏ trống!.
        /// </summary>
        internal static string MessageBoxUserNameNotNull {
            get {
                return ResourceManager.GetString("MessageBoxUserNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập hoặc mật khẩu khống chính xác!.
        /// </summary>
        internal static string MessageBoxUsernameOrPasswordFaill {
            get {
                return ResourceManager.GetString("MessageBoxUsernameOrPasswordFaill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel|*.xls.
        /// </summary>
        internal static string SaveFileExcelFilter {
            get {
                return ResourceManager.GetString("SaveFileExcelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exel 97-2003 Workbook |*.xls.
        /// </summary>
        internal static string SaveFileExelTitle {
            get {
                return ResourceManager.GetString("SaveFileExelTitle", resourceCulture);
            }
        }
    }
}
