using System;
using System.Globalization;
using EducationSkills.Subjects;
using EducationSkills.Data;
using System.Windows.Forms;

namespace EducationSkills
{
    public partial class FormSubjects : DevExpress.XtraEditors.XtraForm
    {
        private readonly EducationSkillsDbContext context;
        public FormSubjects()
        {
            InitializeComponent();
            context = new EducationSkillsDbContext();
            GetAllSubjects();
        }

        private void gridView1_CustomColumnDisplayText(object sender, DevExpress.XtraGrid.Views.Base.CustomColumnDisplayTextEventArgs e)
        {
            if (e.Column.Caption == "#")
            {
                e.DisplayText = (e.ListSourceRowIndex + 1).ToString(CultureInfo.InvariantCulture);
            }
        }

        private void btlRefesh_Click(object sender, EventArgs e)
        {
            GetAllSubjects();
        }

        private void GetAllSubjects()
        {
            // This line of code is generated by Data Source Configuration Wizard
            entityServerModeSource1.QueryableSource = new EducationSkills.Data.EducationSkillsDbContext().PR_Bomon;
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            new FormAddSubject("").ShowDialog();
            GetAllSubjects();
        }

        private void gridView1_RowClick(object sender, DevExpress.XtraGrid.Views.Grid.RowClickEventArgs e)
        {
            //if(e.Clicks > 1)
            //{
            //    string subjectId = (string)gridView1.GetRowCellValue(e.RowHandle, "MaBoMon");
            //    //var model = SubjectDataProvider.GetSubjectById(subjectId);
            //    //    //btnDel.Enabled = true;
            //    new FormAddSubject(subjectId).ShowDialog();
            //    GetAllSubjects();
            //}
        }

        private void gridView1_RowCellClick(object sender, DevExpress.XtraGrid.Views.Grid.RowCellClickEventArgs e)
        {
            if (e.Clicks >= 1)
            {
                string subjectId = (string)gridView1.GetRowCellValue(e.RowHandle, "MaBoMon");
                new FormAddSubject(subjectId).ShowDialog();
                GetAllSubjects();
            }
        }

        private void btnMaximize_Click(object sender, EventArgs e)
        {

            if(WindowState == FormWindowState.Maximized)
            {
                WindowState = FormWindowState.Normal;
            }
            else
            {
                WindowState = FormWindowState.Maximized;
            }
        }
    }
}