//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.Suppliers = new HashSet<Supplier>();
        }
    
        public string AreaID { get; set; }
        public string AreaName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdateBy { get; set; }
    
        public virtual ICollection<Supplier> Suppliers { get; set; }
    }
}
