//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Control
    {
        public Control()
        {
            this.ControlsToRoles = new HashSet<ControlsToRole>();
        }
    
        public string Page { get; set; }
        public string ControlID { get; set; }
    
        public virtual ICollection<ControlsToRole> ControlsToRoles { get; set; }
    }
}
