//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public string ProductID { get; set; }
        public string OrderImportID { get; set; }
        public string OrderExportID { get; set; }
        public System.DateTime InventoryDate { get; set; }
        public Nullable<int> QuantityFirst { get; set; }
        public Nullable<int> QuantityImport { get; set; }
        public Nullable<int> QuantityExport { get; set; }
        public Nullable<int> QuantityInventory { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
