//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderExport
    {
        public OrderExport()
        {
            this.OrderExportDetails = new HashSet<OrderExportDetail>();
        }
    
        public string OrderExportID { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<System.DateTime> ExportDate { get; set; }
        public Nullable<long> Price { get; set; }
        public Nullable<long> Total { get; set; }
        public string Note { get; set; }
        public string CreatedExportBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<OrderExportDetail> OrderExportDetails { get; set; }
    }
}
