//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderImport
    {
        public OrderImport()
        {
            this.OrderImportDetails = new HashSet<OrderImportDetail>();
        }
    
        public string OrderImportID { get; set; }
        public string SupplierID { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Note { get; set; }
        public Nullable<long> Price { get; set; }
        public Nullable<long> TotalMoney { get; set; }
    
        public virtual ICollection<OrderImportDetail> OrderImportDetails { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
