//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderExportDetails = new HashSet<OrderExportDetail>();
            this.OrderImportDetails = new HashSet<OrderImportDetail>();
        }
    
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductGroupID { get; set; }
        public string StockID { get; set; }
        public string UnitID { get; set; }
        public string SupplierID { get; set; }
        public string Barcode { get; set; }
        public string Origin { get; set; }
        public string TaxCode { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public byte[] Image { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<long> Price { get; set; }
        public Nullable<int> ColorID { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual ICollection<OrderExportDetail> OrderExportDetails { get; set; }
        public virtual ICollection<OrderImportDetail> OrderImportDetails { get; set; }
        public virtual ProductGroup ProductGroup { get; set; }
        public virtual Stock Stock { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Inventory Inventory { get; set; }
    }
}
