//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.OrderImports = new HashSet<OrderImport>();
            this.Products = new HashSet<Product>();
        }
    
        public string SupplierID { get; set; }
        public string AreaID { get; set; }
        public string SupplierName { get; set; }
        public string Representatives { get; set; }
        public string PhoneNumber { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string AccountNumber { get; set; }
        public string Bank { get; set; }
        public string TaxCode { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdateBy { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual ICollection<OrderImport> OrderImports { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
