//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeShipping.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IQCDataEntities : DbContext
    {
        public IQCDataEntities()
            : base("name=IQCDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mst_operator> mst_operator { get; set; }
        public virtual DbSet<tbl_test_result> tbl_test_result { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<tbl_test_log> tbl_test_log { get; set; }
        public virtual DbSet<PackingPO> PackingPOes { get; set; }
        public virtual DbSet<Shipping> Shippings { get; set; }
    }
}
