//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeShipping.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QACheck
    {
        public string ProductionID { get; set; }
        public int LineID { get; set; }
        public string BoxID { get; set; }
        public Nullable<System.DateTime> DateCheck { get; set; }
        public Nullable<System.TimeSpan> TimeCheck { get; set; }
        public string OperatorCode { get; set; }
        public Nullable<int> OperationID { get; set; }
        public Nullable<bool> JudgeResult { get; set; }
    }
}
