//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeShipping.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipping
    {
        public System.Guid ID { get; set; }
        public string Operator { get; set; }
        public string Model { get; set; }
        public string WorkingOder { get; set; }
        public int Quantity { get; set; }
        public string BoxID { get; set; }
        public string ProductID { get; set; }
        public System.DateTime DateCheck { get; set; }
        public string MacAddress { get; set; }
        public string PO_NO { get; set; }
    
        public virtual Model Model1 { get; set; }
    }
}
