//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeShipping.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_test_log
    {
        public string ProductionID { get; set; }
        public int LineID { get; set; }
        public string MacAddress { get; set; }
        public string BoxID { get; set; }
        public string ModelID { get; set; }
        public string WorkingOder { get; set; }
        public Nullable<System.DateTime> DateCheck { get; set; }
        public Nullable<System.TimeSpan> TimeCheck { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string OperatorCode { get; set; }
        public bool QA_Check { get; set; }
        public string CheckBy { get; set; }
    
        public virtual Model Model { get; set; }
    }
}
