//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("IndicateReportMasterModel", "FK_ReportDetails_ReportMaster", "ReportMaster", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(IndicateReport.Data.ReportMaster), "ReportDetail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(IndicateReport.Data.ReportDetail), true)]

#endregion

namespace IndicateReport.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class IndicateReportMasterEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new IndicateReportMasterEntities object using the connection string found in the 'IndicateReportMasterEntities' section of the application configuration file.
        /// </summary>
        public IndicateReportMasterEntities() : base("name=IndicateReportMasterEntities", "IndicateReportMasterEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IndicateReportMasterEntities object.
        /// </summary>
        public IndicateReportMasterEntities(string connectionString) : base(connectionString, "IndicateReportMasterEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IndicateReportMasterEntities object.
        /// </summary>
        public IndicateReportMasterEntities(EntityConnection connection) : base(connection, "IndicateReportMasterEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Customer> Customers
        {
            get
            {
                if ((_Customers == null))
                {
                    _Customers = base.CreateObjectSet<Customer>("Customers");
                }
                return _Customers;
            }
        }
        private ObjectSet<Customer> _Customers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Line> Lines
        {
            get
            {
                if ((_Lines == null))
                {
                    _Lines = base.CreateObjectSet<Line>("Lines");
                }
                return _Lines;
            }
        }
        private ObjectSet<Line> _Lines;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Model> Models
        {
            get
            {
                if ((_Models == null))
                {
                    _Models = base.CreateObjectSet<Model>("Models");
                }
                return _Models;
            }
        }
        private ObjectSet<Model> _Models;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ReportMaster> ReportMasters
        {
            get
            {
                if ((_ReportMasters == null))
                {
                    _ReportMasters = base.CreateObjectSet<ReportMaster>("ReportMasters");
                }
                return _ReportMasters;
            }
        }
        private ObjectSet<ReportMaster> _ReportMasters;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ReportDetail> ReportDetails
        {
            get
            {
                if ((_ReportDetails == null))
                {
                    _ReportDetails = base.CreateObjectSet<ReportDetail>("ReportDetails");
                }
                return _ReportDetails;
            }
        }
        private ObjectSet<ReportDetail> _ReportDetails;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomers(Customer customer)
        {
            base.AddObject("Customers", customer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Lines EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLines(Line line)
        {
            base.AddObject("Lines", line);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Models EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToModels(Model model)
        {
            base.AddObject("Models", model);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ReportMasters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReportMasters(ReportMaster reportMaster)
        {
            base.AddObject("ReportMasters", reportMaster);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ReportDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReportDetails(ReportDetail reportDetail)
        {
            base.AddObject("ReportDetails", reportDetail);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IndicateReportMasterModel", Name="Customer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Customer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="cusID">Initial value of the CusID property.</param>
        /// <param name="cusCode">Initial value of the CusCode property.</param>
        /// <param name="cusName">Initial value of the CusName property.</param>
        public static Customer CreateCustomer(global::System.Int32 cusID, global::System.String cusCode, global::System.String cusName)
        {
            Customer customer = new Customer();
            customer.CusID = cusID;
            customer.CusCode = cusCode;
            customer.CusName = cusName;
            return customer;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CusID
        {
            get
            {
                return _CusID;
            }
            set
            {
                if (_CusID != value)
                {
                    OnCusIDChanging(value);
                    ReportPropertyChanging("CusID");
                    _CusID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CusID");
                    OnCusIDChanged();
                }
            }
        }
        private global::System.Int32 _CusID;
        partial void OnCusIDChanging(global::System.Int32 value);
        partial void OnCusIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CusCode
        {
            get
            {
                return _CusCode;
            }
            set
            {
                if (_CusCode != value)
                {
                    OnCusCodeChanging(value);
                    ReportPropertyChanging("CusCode");
                    _CusCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CusCode");
                    OnCusCodeChanged();
                }
            }
        }
        private global::System.String _CusCode;
        partial void OnCusCodeChanging(global::System.String value);
        partial void OnCusCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CusName
        {
            get
            {
                return _CusName;
            }
            set
            {
                OnCusNameChanging(value);
                ReportPropertyChanging("CusName");
                _CusName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CusName");
                OnCusNameChanged();
            }
        }
        private global::System.String _CusName;
        partial void OnCusNameChanging(global::System.String value);
        partial void OnCusNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IndicateReportMasterModel", Name="Line")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Line : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Line object.
        /// </summary>
        /// <param name="lineID">Initial value of the LineID property.</param>
        /// <param name="lineName">Initial value of the LineName property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        public static Line CreateLine(global::System.Int32 lineID, global::System.String lineName, global::System.Boolean isActive)
        {
            Line line = new Line();
            line.LineID = lineID;
            line.LineName = lineName;
            line.IsActive = isActive;
            return line;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LineID
        {
            get
            {
                return _LineID;
            }
            set
            {
                if (_LineID != value)
                {
                    OnLineIDChanging(value);
                    ReportPropertyChanging("LineID");
                    _LineID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LineID");
                    OnLineIDChanged();
                }
            }
        }
        private global::System.Int32 _LineID;
        partial void OnLineIDChanging(global::System.Int32 value);
        partial void OnLineIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LineName
        {
            get
            {
                return _LineName;
            }
            set
            {
                OnLineNameChanging(value);
                ReportPropertyChanging("LineName");
                _LineName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LineName");
                OnLineNameChanged();
            }
        }
        private global::System.String _LineName;
        partial void OnLineNameChanging(global::System.String value);
        partial void OnLineNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IndicateReportMasterModel", Name="Model")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Model : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Model object.
        /// </summary>
        /// <param name="modelID">Initial value of the ModelID property.</param>
        /// <param name="modelCode">Initial value of the ModelCode property.</param>
        /// <param name="modelName">Initial value of the ModelName property.</param>
        public static Model CreateModel(global::System.Int32 modelID, global::System.String modelCode, global::System.String modelName)
        {
            Model model = new Model();
            model.ModelID = modelID;
            model.ModelCode = modelCode;
            model.ModelName = modelName;
            return model;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ModelID
        {
            get
            {
                return _ModelID;
            }
            set
            {
                if (_ModelID != value)
                {
                    OnModelIDChanging(value);
                    ReportPropertyChanging("ModelID");
                    _ModelID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ModelID");
                    OnModelIDChanged();
                }
            }
        }
        private global::System.Int32 _ModelID;
        partial void OnModelIDChanging(global::System.Int32 value);
        partial void OnModelIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ModelCode
        {
            get
            {
                return _ModelCode;
            }
            set
            {
                if (_ModelCode != value)
                {
                    OnModelCodeChanging(value);
                    ReportPropertyChanging("ModelCode");
                    _ModelCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ModelCode");
                    OnModelCodeChanged();
                }
            }
        }
        private global::System.String _ModelCode;
        partial void OnModelCodeChanging(global::System.String value);
        partial void OnModelCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ModelName
        {
            get
            {
                return _ModelName;
            }
            set
            {
                OnModelNameChanging(value);
                ReportPropertyChanging("ModelName");
                _ModelName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ModelName");
                OnModelNameChanged();
            }
        }
        private global::System.String _ModelName;
        partial void OnModelNameChanging(global::System.String value);
        partial void OnModelNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IndicateReportMasterModel", Name="ReportDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ReportDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ReportDetail object.
        /// </summary>
        /// <param name="reportDetailID">Initial value of the ReportDetailID property.</param>
        /// <param name="reportID">Initial value of the ReportID property.</param>
        /// <param name="dateReport">Initial value of the DateReport property.</param>
        public static ReportDetail CreateReportDetail(global::System.Guid reportDetailID, global::System.String reportID, global::System.DateTime dateReport)
        {
            ReportDetail reportDetail = new ReportDetail();
            reportDetail.ReportDetailID = reportDetailID;
            reportDetail.ReportID = reportID;
            reportDetail.DateReport = dateReport;
            return reportDetail;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ReportDetailID
        {
            get
            {
                return _ReportDetailID;
            }
            set
            {
                if (_ReportDetailID != value)
                {
                    OnReportDetailIDChanging(value);
                    ReportPropertyChanging("ReportDetailID");
                    _ReportDetailID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ReportDetailID");
                    OnReportDetailIDChanged();
                }
            }
        }
        private global::System.Guid _ReportDetailID;
        partial void OnReportDetailIDChanging(global::System.Guid value);
        partial void OnReportDetailIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ReportID
        {
            get
            {
                return _ReportID;
            }
            set
            {
                if (_ReportID != value)
                {
                    OnReportIDChanging(value);
                    ReportPropertyChanging("ReportID");
                    _ReportID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ReportID");
                    OnReportIDChanged();
                }
            }
        }
        private global::System.String _ReportID;
        partial void OnReportIDChanging(global::System.String value);
        partial void OnReportIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Total
        {
            get
            {
                return _Total;
            }
            set
            {
                OnTotalChanging(value);
                ReportPropertyChanging("Total");
                _Total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Total");
                OnTotalChanged();
            }
        }
        private Nullable<global::System.Int32> _Total;
        partial void OnTotalChanging(Nullable<global::System.Int32> value);
        partial void OnTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Pass
        {
            get
            {
                return _Pass;
            }
            set
            {
                OnPassChanging(value);
                ReportPropertyChanging("Pass");
                _Pass = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Pass");
                OnPassChanged();
            }
        }
        private Nullable<global::System.Int32> _Pass;
        partial void OnPassChanging(Nullable<global::System.Int32> value);
        partial void OnPassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateReport
        {
            get
            {
                return _DateReport;
            }
            set
            {
                OnDateReportChanging(value);
                ReportPropertyChanging("DateReport");
                _DateReport = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateReport");
                OnDateReportChanged();
            }
        }
        private global::System.DateTime _DateReport;
        partial void OnDateReportChanging(global::System.DateTime value);
        partial void OnDateReportChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IndicateReportMasterModel", "FK_ReportDetails_ReportMaster", "ReportMaster")]
        public ReportMaster ReportMaster
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ReportMaster>("IndicateReportMasterModel.FK_ReportDetails_ReportMaster", "ReportMaster").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ReportMaster>("IndicateReportMasterModel.FK_ReportDetails_ReportMaster", "ReportMaster").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ReportMaster> ReportMasterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ReportMaster>("IndicateReportMasterModel.FK_ReportDetails_ReportMaster", "ReportMaster");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ReportMaster>("IndicateReportMasterModel.FK_ReportDetails_ReportMaster", "ReportMaster", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IndicateReportMasterModel", Name="ReportMaster")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ReportMaster : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ReportMaster object.
        /// </summary>
        /// <param name="reportID">Initial value of the ReportID property.</param>
        public static ReportMaster CreateReportMaster(global::System.String reportID)
        {
            ReportMaster reportMaster = new ReportMaster();
            reportMaster.ReportID = reportID;
            return reportMaster;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ReportID
        {
            get
            {
                return _ReportID;
            }
            set
            {
                if (_ReportID != value)
                {
                    OnReportIDChanging(value);
                    ReportPropertyChanging("ReportID");
                    _ReportID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ReportID");
                    OnReportIDChanged();
                }
            }
        }
        private global::System.String _ReportID;
        partial void OnReportIDChanging(global::System.String value);
        partial void OnReportIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OperatorCode
        {
            get
            {
                return _OperatorCode;
            }
            set
            {
                OnOperatorCodeChanging(value);
                ReportPropertyChanging("OperatorCode");
                _OperatorCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OperatorCode");
                OnOperatorCodeChanged();
            }
        }
        private global::System.String _OperatorCode;
        partial void OnOperatorCodeChanging(global::System.String value);
        partial void OnOperatorCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProcessName
        {
            get
            {
                return _ProcessName;
            }
            set
            {
                OnProcessNameChanging(value);
                ReportPropertyChanging("ProcessName");
                _ProcessName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProcessName");
                OnProcessNameChanged();
            }
        }
        private global::System.String _ProcessName;
        partial void OnProcessNameChanging(global::System.String value);
        partial void OnProcessNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModelName
        {
            get
            {
                return _ModelName;
            }
            set
            {
                OnModelNameChanging(value);
                ReportPropertyChanging("ModelName");
                _ModelName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ModelName");
                OnModelNameChanged();
            }
        }
        private global::System.String _ModelName;
        partial void OnModelNameChanging(global::System.String value);
        partial void OnModelNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Total
        {
            get
            {
                return _Total;
            }
            set
            {
                OnTotalChanging(value);
                ReportPropertyChanging("Total");
                _Total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Total");
                OnTotalChanged();
            }
        }
        private Nullable<global::System.Int32> _Total;
        partial void OnTotalChanging(Nullable<global::System.Int32> value);
        partial void OnTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Pass
        {
            get
            {
                return _Pass;
            }
            set
            {
                OnPassChanging(value);
                ReportPropertyChanging("Pass");
                _Pass = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Pass");
                OnPassChanged();
            }
        }
        private Nullable<global::System.Int32> _Pass;
        partial void OnPassChanging(Nullable<global::System.Int32> value);
        partial void OnPassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateReport
        {
            get
            {
                return _DateReport;
            }
            set
            {
                OnDateReportChanging(value);
                ReportPropertyChanging("DateReport");
                _DateReport = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateReport");
                OnDateReportChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateReport;
        partial void OnDateReportChanging(Nullable<global::System.DateTime> value);
        partial void OnDateReportChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IndicateReportMasterModel", "FK_ReportDetails_ReportMaster", "ReportDetail")]
        public EntityCollection<ReportDetail> ReportDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ReportDetail>("IndicateReportMasterModel.FK_ReportDetails_ReportMaster", "ReportDetail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ReportDetail>("IndicateReportMasterModel.FK_ReportDetails_ReportMaster", "ReportDetail", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
