using System.Data.Entity;

namespace Stock.GUI.Partners
{
    public partial class FormCustomer : DevExpress.XtraEditors.XtraForm
    {
        public FormCustomer()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            Stock.Data.StockACEntities dbContext = new Stock.Data.StockACEntities();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Suppliers.Load();
            // This line of code is generated by Data Source Configuration Wizard
            gridControl1.DataSource = dbContext.Suppliers.Local.ToBindingList();
        }
    }
}